/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ventas;

import controladores.ventas.OyentesMultiplesVenta;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelos.db.SQLVentas;
import utilidades.UtilVentanas;

/**
 *
 * @author jarv
 */
public class PanelVentas extends javax.swing.JPanel {

    public PanelVentas() {
        this(new SQLVentas());
    }
    
    public PanelVentas(SQLVentas sqlVentas) {
        initComponents();
        sqlVentas.setDefaultModeloTablaVenta((DefaultTableModel) this.tablaVentasProductos.getModel());
        addEventos(new OyentesMultiplesVenta(sqlVentas, this));
        sqlVentas.setTablaVentasProductos(tablaVentasProductos);
        this.botonCobrar.setEnabled(false);
    }
    
    public final void addEventos(OyentesMultiplesVenta oyente) {
        UtilVentanas.getVentanaPadre().addKeyListener(oyente);
        this.tablaVentasProductos.addKeyListener(oyente);
        this.campoCodigoBarras.addKeyListener(oyente);
        this.botonAgregarProducto.addActionListener(oyente);
        this.botonBorrarArticulo.addActionListener(oyente);
        this.botonBuscar.addActionListener(oyente);
        this.botonCobrar.addActionListener(oyente);
        this.botonVerificarPrecio.addActionListener(oyente);
        this.campoCodigoBarras.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        panelCentroFuncionesVentas = new javax.swing.JPanel();
        panelFuncionesCodigoBotones = new javax.swing.JPanel();
        panelCodigoDeBarras = new javax.swing.JPanel();
        etiquetaCodigoProducto = new javax.swing.JLabel();
        campoCodigoBarras = new javax.swing.JTextField();
        botonAgregarProducto = new javax.swing.JButton();
        panelBotonesFunciones = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        botonBorrarArticulo = new javax.swing.JButton();
        botonVerificarPrecio = new javax.swing.JButton();
        panelCentroTabla = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tablaVentasProductos = new javax.swing.JTable();
        panelSurCobrar = new javax.swing.JPanel();
        panelGridCobrar = new javax.swing.JPanel();
        panelTextoYBotones = new javax.swing.JPanel();
        etiquetaNumeroProductos = new javax.swing.JLabel();
        panelBotonCobrar = new javax.swing.JPanel();
        botonCobrar = new javax.swing.JButton();
        panelMonto = new javax.swing.JPanel();
        etiquetaMonto = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelCentro.setBackground(new java.awt.Color(255, 153, 102));
        panelCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 24))); // NOI18N
        panelCentro.setLayout(new java.awt.BorderLayout());

        panelCentroFuncionesVentas.setLayout(new java.awt.BorderLayout());

        panelFuncionesCodigoBotones.setLayout(new java.awt.GridLayout(2, 0));

        panelCodigoDeBarras.setBackground(new java.awt.Color(255, 153, 102));

        etiquetaCodigoProducto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaCodigoProducto.setText("Codigo de Producto:");
        panelCodigoDeBarras.add(etiquetaCodigoProducto);

        campoCodigoBarras.setColumns(25);
        campoCodigoBarras.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        campoCodigoBarras.setName("agregarProducto"); // NOI18N
        panelCodigoDeBarras.add(campoCodigoBarras);

        botonAgregarProducto.setBackground(new java.awt.Color(255, 195, 66));
        botonAgregarProducto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/futbolAmericano.png"))); // NOI18N
        botonAgregarProducto.setText("Agregar Producto");
        botonAgregarProducto.setName("botonAgregarProducto"); // NOI18N
        botonAgregarProducto.setPreferredSize(new java.awt.Dimension(209, 40));
        panelCodigoDeBarras.add(botonAgregarProducto);

        panelFuncionesCodigoBotones.add(panelCodigoDeBarras);

        panelBotonesFunciones.setBackground(new java.awt.Color(255, 153, 102));
        panelBotonesFunciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102), 6));
        panelBotonesFunciones.setLayout(new java.awt.GridLayout(1, 0, 10, 5));

        botonBuscar.setBackground(new java.awt.Color(255, 195, 66));
        botonBuscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarPro.png"))); // NOI18N
        botonBuscar.setText("F10 Buscar");
        botonBuscar.setName("botonBuscar"); // NOI18N
        botonBuscar.setPreferredSize(new java.awt.Dimension(209, 40));
        panelBotonesFunciones.add(botonBuscar);

        botonBorrarArticulo.setBackground(new java.awt.Color(255, 195, 66));
        botonBorrarArticulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonBorrarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        botonBorrarArticulo.setText("DEL Borrar Art.");
        botonBorrarArticulo.setName("botonBorrar"); // NOI18N
        botonBorrarArticulo.setPreferredSize(new java.awt.Dimension(209, 40));
        panelBotonesFunciones.add(botonBorrarArticulo);

        botonVerificarPrecio.setBackground(new java.awt.Color(255, 195, 66));
        botonVerificarPrecio.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonVerificarPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio.png"))); // NOI18N
        botonVerificarPrecio.setText("F9 Verificar Precio");
        botonVerificarPrecio.setName("botonVerificar"); // NOI18N
        botonVerificarPrecio.setPreferredSize(new java.awt.Dimension(209, 40));
        panelBotonesFunciones.add(botonVerificarPrecio);

        panelFuncionesCodigoBotones.add(panelBotonesFunciones);

        panelCentroFuncionesVentas.add(panelFuncionesCodigoBotones, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelCentroFuncionesVentas, java.awt.BorderLayout.NORTH);

        panelCentroTabla.setLayout(new java.awt.BorderLayout());

        tablaVentasProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Barras", "Descripción del Producto", "Precio Venta", "Cantidad", "Existencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tablaVentasProductos);

        panelCentroTabla.add(panelTabla, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelCentroTabla, java.awt.BorderLayout.CENTER);

        panelSurCobrar.setLayout(new java.awt.BorderLayout());

        panelGridCobrar.setLayout(new java.awt.BorderLayout());

        panelTextoYBotones.setBackground(new java.awt.Color(255, 211, 173));
        panelTextoYBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102), 15));
        panelTextoYBotones.setForeground(new java.awt.Color(255, 153, 102));
        panelTextoYBotones.setLayout(new java.awt.BorderLayout());

        etiquetaNumeroProductos.setBackground(new java.awt.Color(255, 211, 173));
        etiquetaNumeroProductos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        etiquetaNumeroProductos.setText("    0 Productos en la Venta Actual");
        panelTextoYBotones.add(etiquetaNumeroProductos, java.awt.BorderLayout.CENTER);

        panelBotonCobrar.setBackground(new java.awt.Color(255, 153, 102));
        panelBotonCobrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102), 10));
        panelBotonCobrar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        botonCobrar.setBackground(new java.awt.Color(255, 195, 66));
        botonCobrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobrar.png"))); // NOI18N
        botonCobrar.setText("F12  Cobrar");
        botonCobrar.setName("botonCobrar"); // NOI18N
        botonCobrar.setPreferredSize(new java.awt.Dimension(200, 70));
        panelBotonCobrar.add(botonCobrar);

        panelTextoYBotones.add(panelBotonCobrar, java.awt.BorderLayout.EAST);
        panelBotonCobrar.getAccessibleContext().setAccessibleName("");

        panelGridCobrar.add(panelTextoYBotones, java.awt.BorderLayout.CENTER);

        panelMonto.setBackground(new java.awt.Color(255, 153, 102));
        panelMonto.setLayout(new java.awt.BorderLayout());

        etiquetaMonto.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        etiquetaMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaMonto.setText("$0,00");
        etiquetaMonto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMonto.add(etiquetaMonto, java.awt.BorderLayout.CENTER);

        panelGridCobrar.add(panelMonto, java.awt.BorderLayout.EAST);

        panelSurCobrar.add(panelGridCobrar, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelSurCobrar, java.awt.BorderLayout.SOUTH);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPanel getPanelCentro() {
        return panelCentro;
    }
    
    public JTextField getCampoCodigoBarras() {
        return campoCodigoBarras;
    }
    
    public javax.swing.JLabel getEtiquetaNumeroProductos() {
        return etiquetaNumeroProductos;
    }
    
    public javax.swing.JLabel getEtiquetaMonto() {
        return etiquetaMonto;
    }
    
    public javax.swing.JButton getBotonCobrar() {
        return botonCobrar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarProducto;
    private javax.swing.JButton botonBorrarArticulo;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCobrar;
    private javax.swing.JButton botonVerificarPrecio;
    private javax.swing.JTextField campoCodigoBarras;
    private javax.swing.JLabel etiquetaCodigoProducto;
    private javax.swing.JLabel etiquetaMonto;
    private javax.swing.JLabel etiquetaNumeroProductos;
    private javax.swing.JPanel panelBotonCobrar;
    private javax.swing.JPanel panelBotonesFunciones;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelCentroFuncionesVentas;
    private javax.swing.JPanel panelCentroTabla;
    private javax.swing.JPanel panelCodigoDeBarras;
    private javax.swing.JPanel panelFuncionesCodigoBotones;
    private javax.swing.JPanel panelGridCobrar;
    private javax.swing.JPanel panelMonto;
    private javax.swing.JPanel panelSurCobrar;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JPanel panelTextoYBotones;
    private javax.swing.JTable tablaVentasProductos;
    // End of variables declaration//GEN-END:variables

}
