/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ventas;

import controladores.ventas.OyenteBuscarProducto;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelos.db.SQLVentas;

/**
 *
 * @author jarv
 */
public class VentanaBuscarProducto extends javax.swing.JDialog {

    private JLabel etiquetaMonto;
    private JLabel etiquetaNumeroProductos;

    /**
     * Creates new form VentanaBuscar
     */
    public VentanaBuscarProducto(SQLVentas sqlVentas, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sqlVentas.setDefaultModeloTablaBuscarProducto((DefaultTableModel) this.tablaBuscar.getModel());
        addEventos(new OyenteBuscarProducto(sqlVentas, this));
    }

    public final void addEventos(OyenteBuscarProducto oyente) {
        this.tablaBuscar.addKeyListener(oyente);
        this.botonAceptar.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
        this.botonEliminar.addActionListener(oyente);
        this.botonModificar.addActionListener(oyente);
        this.campoBuscar.addKeyListener(oyente);
        this.campoBuscar.getDocument().addDocumentListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLineBorder = new javax.swing.JPanel();
        panelNorte = new javax.swing.JPanel();
        etiquetaBuscar = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tablaBuscar = new javax.swing.JTable();
        panelSur = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        panelBotonAceptar = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        panelBotonCancelar = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelLineBorder.setBackground(new java.awt.Color(255, 211, 173));
        panelLineBorder.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelLineBorder.setLayout(new java.awt.BorderLayout());

        panelNorte.setBackground(new java.awt.Color(255, 211, 173));
        panelNorte.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaBuscar.setBackground(new java.awt.Color(255, 211, 173));
        etiquetaBuscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaBuscar.setText("Teclee las palabras clave para buscar en toda la descripcion");
        panelNorte.add(etiquetaBuscar);

        campoBuscar.setPreferredSize(new java.awt.Dimension(10, 40));
        panelNorte.add(campoBuscar);

        panelLineBorder.add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setBackground(new java.awt.Color(255, 211, 173));
        panelCentro.setLayout(new java.awt.BorderLayout());

        tablaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Barras", "Descripción del Producto", "Precio Venta", "Categoria", "Inventario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tablaBuscar);

        panelCentro.add(panelTabla, java.awt.BorderLayout.CENTER);

        panelLineBorder.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setBackground(new java.awt.Color(255, 211, 173));
        panelSur.setLayout(new java.awt.BorderLayout());

        panelBotones.setBackground(new java.awt.Color(255, 211, 173));
        panelBotones.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        botonModificar.setBackground(new java.awt.Color(255, 195, 66));
        botonModificar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar (2).png"))); // NOI18N
        botonModificar.setText("Modificar Producto");
        botonModificar.setName("botonModificar"); // NOI18N
        botonModificar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotones.add(botonModificar);

        botonEliminar.setBackground(new java.awt.Color(255, 195, 66));
        botonEliminar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setName("botonEliminar"); // NOI18N
        botonEliminar.setPreferredSize(new java.awt.Dimension(155, 50));
        panelBotones.add(botonEliminar);

        panelSur.add(panelBotones, java.awt.BorderLayout.NORTH);

        panelBotonAceptar.setBackground(new java.awt.Color(255, 211, 173));
        panelBotonAceptar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        botonAceptar.setBackground(new java.awt.Color(255, 195, 66));
        botonAceptar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar (3).png"))); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonAceptar.add(botonAceptar);

        panelSur.add(panelBotonAceptar, java.awt.BorderLayout.WEST);

        panelBotonCancelar.setBackground(new java.awt.Color(255, 211, 173));
        panelBotonCancelar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        botonCancelar.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setText("ESC");
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonCancelar.add(botonCancelar);

        panelSur.add(panelBotonCancelar, java.awt.BorderLayout.EAST);

        panelLineBorder.add(panelSur, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelLineBorder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTablaBuscarProducto() {
        return tablaBuscar;
    }

    public JTextField getCampoBuscarProducto() {
        return campoBuscar;
    }

    public void setEtiquetaMonto(JLabel etiquetaMonto) {
        this.etiquetaMonto = etiquetaMonto;
    }

    public JLabel getEtiquetaMonto() {
        return etiquetaMonto;
    }

    public void setEtiquetaNumeroProducto(JLabel etiquetaNumeroProductos) {
        this.etiquetaNumeroProductos = etiquetaNumeroProductos;
    }

    public JLabel getEtiquetaNumeroProducto() {
        return etiquetaNumeroProductos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JLabel etiquetaBuscar;
    private javax.swing.JPanel panelBotonAceptar;
    private javax.swing.JPanel panelBotonCancelar;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelLineBorder;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaBuscar;
    // End of variables declaration//GEN-END:variables
}
