/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ventas;

import controladores.ventas.OyenteCobrarProducto;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modelos.Venta;
import modelos.db.SQLVentas;

/**
 *
 * @author jarv
 */
public class VentanaCobrarProducto extends javax.swing.JDialog {

    private SQLVentas sqlVentas;
    private JLabel etiquetaNumeroProductosVentas;
    private JLabel etiquetaMontoVentas;
    private JButton botonCobrarProductos;

    /**
     * Creates new form VentanaCobrar
     */
    public VentanaCobrarProducto(SQLVentas sqlVentas, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.sqlVentas = sqlVentas;
        addEventos(new OyenteCobrarProducto(sqlVentas, this));
    }

    public final void addEventos(OyenteCobrarProducto oyente) {
        this.botonCobrar.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
        this.campoCantidadPago.addKeyListener(oyente);
        this.campoCantidadPago.requestFocus();
        this.grupoClienteCliente.addActionListener(oyente);
        this.grupoClientePublicoGeneral.addActionListener(oyente);
        this.grupoClienteCliente.addKeyListener(oyente);
        this.grupoClientePublicoGeneral.addKeyListener(oyente);
        this.addWindowListener(oyente);
        this.campoCantidadPago.getDocument().addDocumentListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoClientes = new javax.swing.ButtonGroup();
        panelLineBorder = new javax.swing.JPanel();
        panelTitledBorder = new javax.swing.JPanel();
        panelBotonesCobrar = new javax.swing.JPanel();
        botonCobrar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaTotalArticulos = new javax.swing.JLabel();
        etiquetaNumeroArticulos = new javax.swing.JLabel();
        panelCobrar = new javax.swing.JPanel();
        panelComponentesCobrar = new javax.swing.JPanel();
        panelBorderCliente = new javax.swing.JPanel();
        panelTipoCliente = new javax.swing.JPanel();
        grupoClientePublicoGeneral = new javax.swing.JRadioButton();
        grupoClienteCliente = new javax.swing.JRadioButton();
        etiquetaNombreCliente = new javax.swing.JLabel();
        etiquetaCantidadMonto = new javax.swing.JLabel();
        panelCamposCambio = new javax.swing.JPanel();
        panelCampoCantidadPago = new javax.swing.JPanel();
        etiquetaPagoCon = new javax.swing.JLabel();
        campoCantidadPago = new javax.swing.JTextField();
        panelTextoCambio = new javax.swing.JPanel();
        etiquetaCambio = new javax.swing.JLabel();
        etiquetaCantidadCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelLineBorder.setBackground(new java.awt.Color(255, 195, 66));
        panelLineBorder.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelLineBorder.setLayout(new java.awt.BorderLayout());

        panelTitledBorder.setBackground(new java.awt.Color(255, 211, 173));
        panelTitledBorder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 36))); // NOI18N

        panelBotonesCobrar.setBackground(new java.awt.Color(255, 211, 173));
        panelBotonesCobrar.setLayout(new java.awt.GridLayout(4, 0));

        botonCobrar.setBackground(new java.awt.Color(255, 195, 66));
        botonCobrar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobrar.png"))); // NOI18N
        botonCobrar.setText("F2 - Cobrar");
        botonCobrar.setName("botonCobrar"); // NOI18N
        botonCobrar.setPreferredSize(new java.awt.Dimension(120, 50));
        panelBotonesCobrar.add(botonCobrar);

        botonCancelar.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setText("ESC");
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(120, 50));
        panelBotonesCobrar.add(botonCancelar);

        etiquetaTotalArticulos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        etiquetaTotalArticulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTotalArticulos.setText("Total de Articulos:");
        panelBotonesCobrar.add(etiquetaTotalArticulos);

        etiquetaNumeroArticulos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        etiquetaNumeroArticulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNumeroArticulos.setText("0");
        panelBotonesCobrar.add(etiquetaNumeroArticulos);

        panelTitledBorder.add(panelBotonesCobrar);

        panelLineBorder.add(panelTitledBorder, java.awt.BorderLayout.EAST);

        panelCobrar.setBackground(new java.awt.Color(255, 211, 173));
        panelCobrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cobrar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myanmar Text", 1, 30))); // NOI18N
        panelCobrar.setLayout(new java.awt.BorderLayout());

        panelComponentesCobrar.setBackground(new java.awt.Color(255, 211, 173));
        panelComponentesCobrar.setLayout(new java.awt.GridLayout(3, 0));

        panelBorderCliente.setBackground(new java.awt.Color(255, 211, 173));
        panelBorderCliente.setLayout(new java.awt.BorderLayout());

        panelTipoCliente.setBackground(new java.awt.Color(255, 211, 173));

        grupoClientePublicoGeneral.setBackground(new java.awt.Color(255, 211, 173));
        grupoClientes.add(grupoClientePublicoGeneral);
        grupoClientePublicoGeneral.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        grupoClientePublicoGeneral.setSelected(true);
        grupoClientePublicoGeneral.setText("Publico en General");
        grupoClientePublicoGeneral.setActionCommand("publicoGeneral");
        grupoClientePublicoGeneral.setName("publicoGeneral"); // NOI18N
        panelTipoCliente.add(grupoClientePublicoGeneral);

        grupoClienteCliente.setBackground(new java.awt.Color(255, 211, 173));
        grupoClientes.add(grupoClienteCliente);
        grupoClienteCliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        grupoClienteCliente.setText("Cliente");
        grupoClienteCliente.setActionCommand("cliente");
        grupoClienteCliente.setName("cliente"); // NOI18N
        panelTipoCliente.add(grupoClienteCliente);

        panelBorderCliente.add(panelTipoCliente, java.awt.BorderLayout.NORTH);

        etiquetaNombreCliente.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        etiquetaNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombreCliente.setText("PUBLICO EN GENERAL");
        panelBorderCliente.add(etiquetaNombreCliente, java.awt.BorderLayout.CENTER);

        panelComponentesCobrar.add(panelBorderCliente);

        etiquetaCantidadMonto.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        etiquetaCantidadMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCantidadMonto.setText("$0.0");
        panelComponentesCobrar.add(etiquetaCantidadMonto);

        panelCamposCambio.setBackground(new java.awt.Color(255, 211, 173));
        panelCamposCambio.setLayout(new java.awt.BorderLayout());

        panelCampoCantidadPago.setBackground(new java.awt.Color(255, 211, 173));
        panelCampoCantidadPago.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        etiquetaPagoCon.setBackground(new java.awt.Color(255, 211, 173));
        etiquetaPagoCon.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiquetaPagoCon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaPagoCon.setText("Pago con:");
        panelCampoCantidadPago.add(etiquetaPagoCon);

        campoCantidadPago.setColumns(10);
        panelCampoCantidadPago.add(campoCantidadPago);

        panelCamposCambio.add(panelCampoCantidadPago, java.awt.BorderLayout.NORTH);

        panelTextoCambio.setBackground(new java.awt.Color(255, 211, 173));
        panelTextoCambio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        etiquetaCambio.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        etiquetaCambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaCambio.setText("Su Cambio:");
        panelTextoCambio.add(etiquetaCambio);

        etiquetaCantidadCambio.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        etiquetaCantidadCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCantidadCambio.setText("$0.0");
        panelTextoCambio.add(etiquetaCantidadCambio);

        panelCamposCambio.add(panelTextoCambio, java.awt.BorderLayout.CENTER);

        panelComponentesCobrar.add(panelCamposCambio);

        panelCobrar.add(panelComponentesCobrar, java.awt.BorderLayout.CENTER);

        panelLineBorder.add(panelCobrar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelLineBorder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JLabel getEtiquetaCantidadCambio() {
        return etiquetaCantidadCambio;
    }

    /**
     * @return the botonCobrarProductos
     */
    public JButton getBotonCobrarProductos() {
        return botonCobrarProductos;
    }

    /**
     * @param botonCobrarProductos the botonCobrarProductos to set
     */
    public void setBotonCobrarProductos(JButton botonCobrarProductos) {
        this.botonCobrarProductos = botonCobrarProductos;
    }

    public javax.swing.JLabel getEtiquetaCantidadMonto() {
        return etiquetaCantidadMonto;
    }

    public javax.swing.JLabel getEtiquetaNumeroArticulos() {
        return etiquetaNumeroArticulos;
    }

    public javax.swing.JTextField getCampoCantidadPago() {
        return campoCantidadPago;
    }

    public javax.swing.ButtonGroup getGrupoClientes() {
        return grupoClientes;
    }

    public javax.swing.JLabel getEtiquetaNombreCliente() {
        return etiquetaNombreCliente;
    }

    public void setEtiquetaNumeroProductosVentas(JLabel etiquetaNumeroProductosVentas) {
        this.etiquetaNumeroProductosVentas = etiquetaNumeroProductosVentas;
    }

    public javax.swing.JLabel getEtiquetaNumeroProductosVentas() {
        return etiquetaNumeroProductosVentas;
    }

    public void setEtiquetaMontoVentas(JLabel etiquetaMontoVentas) {
        this.etiquetaMontoVentas = etiquetaMontoVentas;
    }

    public JLabel getEtiquetaMontoVentas() {
        return etiquetaMontoVentas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCobrar;
    private javax.swing.JTextField campoCantidadPago;
    private javax.swing.JLabel etiquetaCambio;
    private javax.swing.JLabel etiquetaCantidadCambio;
    private javax.swing.JLabel etiquetaCantidadMonto;
    private javax.swing.JLabel etiquetaNombreCliente;
    private javax.swing.JLabel etiquetaNumeroArticulos;
    private javax.swing.JLabel etiquetaPagoCon;
    private javax.swing.JLabel etiquetaTotalArticulos;
    private javax.swing.JRadioButton grupoClienteCliente;
    private javax.swing.JRadioButton grupoClientePublicoGeneral;
    private javax.swing.ButtonGroup grupoClientes;
    private javax.swing.JPanel panelBorderCliente;
    private javax.swing.JPanel panelBotonesCobrar;
    private javax.swing.JPanel panelCampoCantidadPago;
    private javax.swing.JPanel panelCamposCambio;
    private javax.swing.JPanel panelCobrar;
    private javax.swing.JPanel panelComponentesCobrar;
    private javax.swing.JPanel panelLineBorder;
    private javax.swing.JPanel panelTextoCambio;
    private javax.swing.JPanel panelTipoCliente;
    private javax.swing.JPanel panelTitledBorder;
    // End of variables declaration//GEN-END:variables
}
