/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ventas;

import controladores.ventas.OyenteVerificador;
import javax.swing.JLabel;
import modelos.db.SQLVentas;

/**
 *
 * @author jarv
 */
public class VentanaVerificador extends javax.swing.JDialog {

    private JLabel etiquetaMonto;
    private JLabel etiquetaNumeroProductos;

    /**
     * Creates new form VentanaBuscar
     */
    public VentanaVerificador(SQLVentas sqlVentas, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addEventos(new OyenteVerificador(sqlVentas, this));
    }

    public final void addEventos(OyenteVerificador oyente) {
        this.campoVerificarPrecio.addKeyListener(oyente);
        this.campoVerificarPrecio.addActionListener(oyente);
        this.botonAgregarVenta.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLineBorder = new javax.swing.JPanel();
        panelNorte = new javax.swing.JPanel();
        etiquetaVerificarPrecio = new javax.swing.JLabel();
        campoVerificarPrecio = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        etiquetaDescripcionProducto = new javax.swing.JLabel();
        etiquetaPrecio = new javax.swing.JLabel();
        panelSur = new javax.swing.JPanel();
        panelBotonAgregar = new javax.swing.JPanel();
        botonAgregarVenta = new javax.swing.JButton();
        panelBotonCancelar = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelLineBorder.setBackground(new java.awt.Color(255, 211, 173));
        panelLineBorder.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelLineBorder.setLayout(new java.awt.BorderLayout());

        panelNorte.setBackground(new java.awt.Color(255, 211, 173));
        panelNorte.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaVerificarPrecio.setBackground(new java.awt.Color(255, 211, 173));
        etiquetaVerificarPrecio.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        etiquetaVerificarPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaVerificarPrecio.setText("Verificador de Precios");
        panelNorte.add(etiquetaVerificarPrecio);

        campoVerificarPrecio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        campoVerificarPrecio.setName("campoVerificarPrecio"); // NOI18N
        campoVerificarPrecio.setPreferredSize(new java.awt.Dimension(10, 40));
        panelNorte.add(campoVerificarPrecio);

        panelLineBorder.add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setBackground(new java.awt.Color(255, 211, 173));
        panelCentro.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaDescripcionProducto.setBackground(new java.awt.Color(255, 211, 173));
        etiquetaDescripcionProducto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        etiquetaDescripcionProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDescripcionProducto.setText("DESCRIPCION DEL PRODUCTO");
        panelCentro.add(etiquetaDescripcionProducto);

        etiquetaPrecio.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        etiquetaPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaPrecio.setText("$0.0");
        panelCentro.add(etiquetaPrecio);

        panelLineBorder.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setBackground(new java.awt.Color(255, 211, 173));
        panelSur.setLayout(new java.awt.BorderLayout());

        panelBotonAgregar.setBackground(new java.awt.Color(255, 211, 173));
        panelBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 211, 173), 10));
        panelBotonAgregar.setLayout(new java.awt.GridLayout());

        botonAgregarVenta.setBackground(new java.awt.Color(255, 195, 66));
        botonAgregarVenta.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonAgregarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio.png"))); // NOI18N
        botonAgregarVenta.setText("F1 - Agregar a Venta");
        botonAgregarVenta.setName("botonAgregarVenta"); // NOI18N
        botonAgregarVenta.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonAgregar.add(botonAgregarVenta);

        panelSur.add(panelBotonAgregar, java.awt.BorderLayout.CENTER);

        panelBotonCancelar.setBackground(new java.awt.Color(255, 211, 173));
        panelBotonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 211, 173), 5));
        panelBotonCancelar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        botonCancelar.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setText("ESC - Cancelar");
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonCancelar.add(botonCancelar);

        panelSur.add(panelBotonCancelar, java.awt.BorderLayout.EAST);

        panelLineBorder.add(panelSur, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelLineBorder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JTextField getCampoVerificarPrecio() {
        return campoVerificarPrecio;
    }

    public javax.swing.JLabel getEtiquetaPrecio() {
        return etiquetaPrecio;
    }

    public javax.swing.JLabel getEtiquetaDescripcionProducto() {
        return etiquetaDescripcionProducto;
    }

    public void setEtiquetaMonto(JLabel etiquetaMonto) {
        this.etiquetaMonto = etiquetaMonto;
    }

    public JLabel getEtiquetaMonto() {
        return etiquetaMonto;
    }

    public void setEtiquetaNumeroProducto(JLabel etiquetaNumeroProductos) {
        this.etiquetaNumeroProductos = etiquetaNumeroProductos;
    }

    public JLabel getEtiquetaNumeroProducto() {
        return etiquetaNumeroProductos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarVenta;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoVerificarPrecio;
    private javax.swing.JLabel etiquetaDescripcionProducto;
    private javax.swing.JLabel etiquetaPrecio;
    private javax.swing.JLabel etiquetaVerificarPrecio;
    private javax.swing.JPanel panelBotonAgregar;
    private javax.swing.JPanel panelBotonCancelar;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelLineBorder;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    // End of variables declaration//GEN-END:variables
}
