/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.OyenteBotonesSecciones;
import java.awt.Color;
import javax.swing.JLabel;
import modelos.db.SQLVentas;
import vistas.ventas.PanelVentas;

/**
 *
 * @author jarv
 */
public class PanelSecciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelVentas
     */
    public PanelSecciones() {
        initComponents();
        this.botonVentas.setEnabled(false);
        OyenteBotonesSecciones oyente = new OyenteBotonesSecciones(this);
        System.out.println(PanelLogin.getUsuario());
        this.etiquetaUsuario.setText(PanelLogin.getUsuario());
        addEventos(oyente);
    }
    
    public final void addEventos(OyenteBotonesSecciones oyente) {
        this.botonVentas.addActionListener(oyente);
        this.botonClientes.addActionListener(oyente);
        this.botonProductos.addActionListener(oyente);
        this.botonUsuarios.addActionListener(oyente);
        this.botonSalir.addActionListener(oyente);
        this.botonReportes.addActionListener(oyente);
        //this.botonProveedores.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        panelNorteBotonesSecciones = new javax.swing.JPanel();
        panelNorteMenu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etiquetaUsuario = new javax.swing.JLabel();
        panelSurBotones = new javax.swing.JPanel();
        botonUsuarios = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        botonVentas = new javax.swing.JButton();
        botonProductos = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 153, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 15));
        setLayout(new java.awt.BorderLayout());

        panelNorte.setBackground(new java.awt.Color(255, 153, 0));
        panelNorte.setLayout(new java.awt.BorderLayout());

        panelNorteBotonesSecciones.setLayout(new java.awt.BorderLayout());

        panelNorteMenu.setBackground(new java.awt.Color(255, 102, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basketball_icon-icons.com_67241.png"))); // NOI18N
        panelNorteMenu.add(jLabel9);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boxing_icon-icons.com_67239.png"))); // NOI18N
        panelNorteMenu.add(jLabel8);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cycling_mountain_bike_icon-icons.com_67235.png"))); // NOI18N
        panelNorteMenu.add(jLabel3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/football_icon-icons.com_67229 (1).png"))); // NOI18N
        panelNorteMenu.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 48)); // NOI18N
        jLabel1.setText("Menu Principal");
        panelNorteMenu.add(jLabel1);

        etiquetaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaUsuario.setText("USUARIO: name");
        panelNorteMenu.add(etiquetaUsuario);

        panelNorteBotonesSecciones.add(panelNorteMenu, java.awt.BorderLayout.NORTH);

        panelSurBotones.setBackground(new java.awt.Color(255, 102, 102));
        panelSurBotones.setLayout(new java.awt.GridLayout(1, 0, 4, 0));

        botonUsuarios.setBackground(new java.awt.Color(252, 215, 136));
        botonUsuarios.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        botonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        botonUsuarios.setText("Usuarios");
        botonUsuarios.setFocusable(false);
        botonUsuarios.setName("seccionUsuarios"); // NOI18N
        botonUsuarios.setPreferredSize(new java.awt.Dimension(105, 50));
        panelSurBotones.add(botonUsuarios);

        botonClientes.setBackground(new java.awt.Color(252, 215, 136));
        botonClientes.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        botonClientes.setText("Clientes");
        botonClientes.setFocusable(false);
        botonClientes.setName("seccionClientes"); // NOI18N
        botonClientes.setPreferredSize(new java.awt.Dimension(105, 50));
        panelSurBotones.add(botonClientes);

        botonVentas.setBackground(new java.awt.Color(252, 215, 136));
        botonVentas.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        botonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        botonVentas.setText("Ventas");
        botonVentas.setFocusable(false);
        botonVentas.setName("seccionVentas"); // NOI18N
        botonVentas.setPreferredSize(new java.awt.Dimension(105, 50));
        panelSurBotones.add(botonVentas);

        botonProductos.setBackground(new java.awt.Color(252, 215, 136));
        botonProductos.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        botonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/futbolAmericano.png"))); // NOI18N
        botonProductos.setText("Productos");
        botonProductos.setFocusable(false);
        botonProductos.setName("seccionProductos"); // NOI18N
        botonProductos.setPreferredSize(new java.awt.Dimension(105, 50));
        panelSurBotones.add(botonProductos);

        botonReportes.setBackground(new java.awt.Color(252, 215, 136));
        botonReportes.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        botonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        botonReportes.setText("Reportes");
        botonReportes.setFocusable(false);
        botonReportes.setName("seccionReportes"); // NOI18N
        botonReportes.setPreferredSize(new java.awt.Dimension(105, 50));
        panelSurBotones.add(botonReportes);

        botonSalir.setBackground(new java.awt.Color(252, 215, 136));
        botonSalir.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir (2).png"))); // NOI18N
        botonSalir.setFocusable(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setName("botonSalir"); // NOI18N
        botonSalir.setPreferredSize(new java.awt.Dimension(105, 50));
        panelSurBotones.add(botonSalir);

        panelNorteBotonesSecciones.add(panelSurBotones, java.awt.BorderLayout.SOUTH);

        panelNorte.add(panelNorteBotonesSecciones, java.awt.BorderLayout.NORTH);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setBackground(new java.awt.Color(255, 102, 0));
        panelCentro.setLayout(new java.awt.BorderLayout());
        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPanel getPanelCentro() {
        return panelCentro;
    }
    
    public javax.swing.JPanel getPanelNorteBotonesSecciones() {
        return panelNorteBotonesSecciones;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonProductos;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JButton botonVentas;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelNorteBotonesSecciones;
    private javax.swing.JPanel panelNorteMenu;
    private javax.swing.JPanel panelSurBotones;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelSurBotones
     */
    public javax.swing.JPanel getPanelSurBotones() {
        return panelSurBotones;
    }
    
    public JLabel getEtiquetaUsuario() {
        return etiquetaUsuario;
    }

}
