/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.OyenteLogin;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import modelos.db.SQLogin;

/**
 *
 * @author jarv
 */
public class PanelLogin extends javax.swing.JPanel {
    
    private javax.swing.JButton botonLogin;
    private javax.swing.JPasswordField campoContrasena;
    private javax.swing.JTextField campoUsuario;
    private static String nombre;

    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
        addComponentes();
        addEventos(new OyenteLogin(new SQLogin(), this));
    }
    
    public static void setUsuario(String nombre) {
        PanelLogin.nombre = nombre;
    }
    
    public static String getUsuario() {
        return nombre;
    }
    
    public final void addEventos(OyenteLogin oyente) {
        botonLogin.addActionListener(oyente);
        campoContrasena.addActionListener(oyente);
        campoUsuario.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPasswordField getCampoContrasena() {
        return campoContrasena;
    }
    
    public javax.swing.JTextField getCampoUsuario() {
        return campoUsuario;
    }
    
    private final void addComponentes() {
        
        setBounds(100, 100, 450, 450);
        setBorder(new EmptyBorder(5, 5, 5, 5));

        JLabel lblLogo = new JLabel("Logo");
        lblLogo.setBounds(167, 21, 125, 125);
        URL url = getClass().getResource("/imagenes/logo.png");
        lblLogo.setIcon(ajustaTamanoImagen(url.getPath(), lblLogo));
        add(lblLogo);

        JLabel lblUser = new JLabel("user");
        lblUser.setBounds(95, 192, 20, 25);
        url = getClass().getResource("/imagenes/user.png");
        lblUser.setIcon(ajustaTamanoImagen(url.getPath(), lblUser));
        add(lblUser);

        JLabel lblPass = new JLabel("pass");
        lblPass.setBounds(95, 267, 20, 25);
        url = getClass().getResource("/imagenes/password.png");
        lblPass.setIcon(ajustaTamanoImagen(url.getPath(), lblPass));
        add(lblPass);

        campoUsuario = new JTextField();
        campoUsuario.setName("campoUsuario");
        campoUsuario.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        campoUsuario.setBounds(128, 182, 232, 45);
        campoUsuario.setBorder(null);
        add(campoUsuario);
        campoUsuario.setColumns(10);

        JLabel lblNewLabel = new JLabel("Usuario");
        lblNewLabel.setBounds(86, 182, 281, 45);
        url = getClass().getResource("/imagenes/campo.png");
        lblNewLabel.setIcon(ajustaTamanoImagen(url.getPath(), lblNewLabel));
        add(lblNewLabel);

        campoContrasena = new JPasswordField();
        campoContrasena.setName("campoContrasena");
        campoContrasena.setFont(new Font("Lucida Grande", Font.PLAIN, 16));

        campoContrasena.setColumns(10);
        campoContrasena.setBounds(127, 258, 232, 45);
        campoContrasena.setBorder(null);
        add(campoContrasena);

        JLabel label = new JLabel("Contrasena");
        label.setBounds(86, 258, 281, 45);
        url = getClass().getResource("/imagenes/campo.png");
        label.setIcon(ajustaTamanoImagen(url.getPath(), label));
        add(label);

        botonLogin = new JButton("Iniciar Sesion");
        botonLogin.setName("botonIniciarSesion");
        botonLogin.setBackground(new Color(0, 171, 197));
        botonLogin.setBounds(250 - 30, 359 - 30, 117, 29);
        botonLogin.setSize(new Dimension(150, 50));
        add(botonLogin);
    }
    
    public static ImageIcon ajustaTamanoImagen(String ruta, JLabel label_2) {
        Image img = new ImageIcon(ruta).getImage();
        return new ImageIcon(img.getScaledInstance(label_2.getWidth(), label_2.getHeight(), Image.SCALE_SMOOTH));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
