/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.clientes;

import controladores.clientes.OyenteNuevoCliente;
import modelos.db.SQLClientes;

/**
 *
 * @author jarv
 */
public class PanelNuevoCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuevoCliente
     */
    public PanelNuevoCliente(SQLClientes sqlClientes) {
        initComponents();
        addEventos(new OyenteNuevoCliente(sqlClientes, this));
    }

    public final void addEventos(OyenteNuevoCliente oyente) {
        this.botonGuardarCliente.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGrupoSexo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        panelNorteNuevoCliente = new javax.swing.JPanel();
        etiquetaNuevoCliente = new javax.swing.JLabel();
        etiquetaInformacion = new javax.swing.JLabel();
        panelCentroCampos = new javax.swing.JPanel();
        panelEtiquetas = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaApellidoP = new javax.swing.JLabel();
        etiquetaApellidoM = new javax.swing.JLabel();
        etiquetaSexo = new javax.swing.JLabel();
        etiquetaTelefono = new javax.swing.JLabel();
        etiquetaEmail = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        campoNombre = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        panelSexo = new javax.swing.JPanel();
        radioBotonM = new javax.swing.JRadioButton();
        radioBotonF = new javax.swing.JRadioButton();
        radioBotonOtro = new javax.swing.JRadioButton();
        campoTelefono = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        panelSurBotones = new javax.swing.JPanel();
        botonGuardarCliente = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(192, 236, 245));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorteNuevoCliente.setBackground(new java.awt.Color(192, 236, 245));
        panelNorteNuevoCliente.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaNuevoCliente.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaNuevoCliente.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        etiquetaNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNuevoCliente.setText("Nuevo Cliente");
        panelNorteNuevoCliente.add(etiquetaNuevoCliente);

        etiquetaInformacion.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaInformacion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaInformacion.setText("- Llene la siguiente información acerca del cliente");
        panelNorteNuevoCliente.add(etiquetaInformacion);

        add(panelNorteNuevoCliente, java.awt.BorderLayout.NORTH);

        panelCentroCampos.setLayout(new java.awt.BorderLayout());

        panelEtiquetas.setBackground(new java.awt.Color(192, 236, 245));
        panelEtiquetas.setLayout(new java.awt.GridLayout(6, 1, 0, 7));

        etiquetaNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        etiquetaNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNombre.setText("Nombre:");
        panelEtiquetas.add(etiquetaNombre);

        etiquetaApellidoP.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        etiquetaApellidoP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoP.setText("Apellido Paterno:");
        panelEtiquetas.add(etiquetaApellidoP);

        etiquetaApellidoM.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        etiquetaApellidoM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoM.setText("Apellido Materno:");
        panelEtiquetas.add(etiquetaApellidoM);

        etiquetaSexo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        etiquetaSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaSexo.setText("Sexo:");
        panelEtiquetas.add(etiquetaSexo);

        etiquetaTelefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        etiquetaTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaTelefono.setText("Telefono:");
        panelEtiquetas.add(etiquetaTelefono);

        etiquetaEmail.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaEmail.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        etiquetaEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaEmail.setText("Email:");
        panelEtiquetas.add(etiquetaEmail);

        panelCentroCampos.add(panelEtiquetas, java.awt.BorderLayout.WEST);

        panelCampos.setBackground(new java.awt.Color(192, 236, 245));
        panelCampos.setLayout(new java.awt.GridLayout(6, 1, 0, 7));

        campoNombre.setColumns(20);
        panelCampos.add(campoNombre);

        campoApellidoP.setColumns(20);
        panelCampos.add(campoApellidoP);

        campoApellidoM.setColumns(20);
        panelCampos.add(campoApellidoM);

        panelSexo.setBackground(new java.awt.Color(192, 236, 245));
        panelSexo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 1));

        radioBotonM.setBackground(new java.awt.Color(192, 236, 245));
        botonGrupoSexo.add(radioBotonM);
        radioBotonM.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        radioBotonM.setText("M");
        radioBotonM.setActionCommand("m");
        panelSexo.add(radioBotonM);

        radioBotonF.setBackground(new java.awt.Color(192, 236, 245));
        botonGrupoSexo.add(radioBotonF);
        radioBotonF.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        radioBotonF.setText("F");
        radioBotonF.setActionCommand("f");
        panelSexo.add(radioBotonF);

        radioBotonOtro.setBackground(new java.awt.Color(192, 236, 245));
        botonGrupoSexo.add(radioBotonOtro);
        radioBotonOtro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        radioBotonOtro.setText("Otro");
        radioBotonOtro.setActionCommand("otro");
        panelSexo.add(radioBotonOtro);

        panelCampos.add(panelSexo);

        campoTelefono.setColumns(20);
        panelCampos.add(campoTelefono);

        campoEmail.setColumns(20);
        panelCampos.add(campoEmail);

        panelCentroCampos.add(panelCampos, java.awt.BorderLayout.CENTER);

        add(panelCentroCampos, java.awt.BorderLayout.CENTER);

        panelSurBotones.setBackground(new java.awt.Color(192, 236, 245));
        panelSurBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botonGuardarCliente.setBackground(new java.awt.Color(255, 195, 66));
        botonGuardarCliente.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardado.png"))); // NOI18N
        botonGuardarCliente.setText("Guardar");
        botonGuardarCliente.setName("botonGuardar"); // NOI18N
        botonGuardarCliente.setPreferredSize(new java.awt.Dimension(141, 50));
        panelSurBotones.add(botonGuardarCliente);

        botonCancelar.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(98, 50));
        panelSurBotones.add(botonCancelar);

        add(panelSurBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the campoApellidoM
     */
    public javax.swing.JTextField getCampoApellidoM() {
        return campoApellidoM;
    }

    /**
     * @return the campoApellidoP
     */
    public javax.swing.JTextField getCampoApellidoP() {
        return campoApellidoP;
    }

    /**
     * @return the campoEmail
     */
    public javax.swing.JTextField getCampoEmail() {
        return campoEmail;
    }

    /**
     * @return the campoNombre
     */
    public javax.swing.JTextField getCampoNombre() {
        return campoNombre;
    }

    /**
     * @return the campoTelefono
     */
    public javax.swing.JTextField getCampoTelefono() {
        return campoTelefono;
    }

    /**
     * @return the botonGrupoSexo
     */
    public javax.swing.ButtonGroup getBotonGrupoSexo() {
        return botonGrupoSexo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.ButtonGroup botonGrupoSexo;
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel etiquetaApellidoM;
    private javax.swing.JLabel etiquetaApellidoP;
    private javax.swing.JLabel etiquetaEmail;
    private javax.swing.JLabel etiquetaInformacion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNuevoCliente;
    private javax.swing.JLabel etiquetaSexo;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelCentroCampos;
    private javax.swing.JPanel panelEtiquetas;
    private javax.swing.JPanel panelNorteNuevoCliente;
    private javax.swing.JPanel panelSexo;
    private javax.swing.JPanel panelSurBotones;
    private javax.swing.JRadioButton radioBotonF;
    private javax.swing.JRadioButton radioBotonM;
    private javax.swing.JRadioButton radioBotonOtro;
    // End of variables declaration//GEN-END:variables

}
