/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.clientes;

import controladores.clientes.OyenteBotonesClientes;
import java.awt.Color;
import javax.swing.JPanel;
import modelos.db.SQLClientes;

/**
 *
 * @author jarv
 */
public class PanelClientes extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        initComponents();
        
        SQLClientes sqlClientes = new SQLClientes();
        OyenteBotonesClientes oyente = new OyenteBotonesClientes(sqlClientes, this);
        addEventos(oyente);
        this.botonNuevoCliente.setEnabled(false);
    }

    public final void addEventos(OyenteBotonesClientes oyente) {
        this.botonEliminarCliente.addActionListener(oyente);
        this.botonModificarCliente.addActionListener(oyente);
        this.botonNuevoCliente.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        botonNuevoCliente = new javax.swing.JButton();
        botonModificarCliente = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();

        setBackground(new java.awt.Color(116, 215, 205));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 0, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        panelNorte.setBackground(new java.awt.Color(116, 215, 205));

        botonNuevoCliente.setBackground(new java.awt.Color(255, 195, 66));
        botonNuevoCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        botonNuevoCliente.setText("Añadir");
        botonNuevoCliente.setFocusable(false);
        botonNuevoCliente.setName("nuevoCliente"); // NOI18N
        botonNuevoCliente.setPreferredSize(new java.awt.Dimension(150, 50));
        panelNorte.add(botonNuevoCliente);

        botonModificarCliente.setBackground(new java.awt.Color(255, 195, 66));
        botonModificarCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        botonModificarCliente.setText("Modificar");
        botonModificarCliente.setFocusable(false);
        botonModificarCliente.setName("modificarCliente"); // NOI18N
        botonModificarCliente.setPreferredSize(new java.awt.Dimension(150, 50));
        panelNorte.add(botonModificarCliente);

        botonEliminarCliente.setBackground(new java.awt.Color(255, 195, 66));
        botonEliminarCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botonEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        botonEliminarCliente.setText("Borrar");
        botonEliminarCliente.setFocusable(false);
        botonEliminarCliente.setName("eliminarCliente"); // NOI18N
        botonEliminarCliente.setPreferredSize(new java.awt.Dimension(150, 50));
        panelNorte.add(botonEliminarCliente);

        add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelCentro.setBackground(new java.awt.Color(192, 236, 245));
        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelCentro() {
        return panelCentro;
    }
    
    public JPanel getPanelNorte() {
        return panelNorte;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonModificarCliente;
    private javax.swing.JButton botonNuevoCliente;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    // End of variables declaration//GEN-END:variables
}
