/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.clientes;

import controladores.clientes.OyenteEliminarCliente;
import modelos.db.SQLClientes;

/**
 *
 * @author jarv
 */
public class PanelEliminarCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelModificarCliente
     */
    public PanelEliminarCliente(SQLClientes sqlClientes) {
        initComponents();
        addEventos(new OyenteEliminarCliente(sqlClientes, this));
    }

    public final void addEventos(OyenteEliminarCliente oyente) {
        this.botonAceptar.addActionListener(oyente);
        this.campoCliente.getDocument().addDocumentListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorteTextos = new javax.swing.JPanel();
        etiquetaEliminarCliente = new javax.swing.JLabel();
        etiquetaInformacionEliminar = new javax.swing.JLabel();
        panelCentroTabla = new javax.swing.JPanel();
        campoCliente = new javax.swing.JTextField();
        panelTabla = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        panelBoton = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(192, 236, 245));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorteTextos.setBackground(new java.awt.Color(192, 236, 245));
        panelNorteTextos.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaEliminarCliente.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaEliminarCliente.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        etiquetaEliminarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaEliminarCliente.setText("Eliminar Cliente");
        panelNorteTextos.add(etiquetaEliminarCliente);

        etiquetaInformacionEliminar.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaInformacionEliminar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaInformacionEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaInformacionEliminar.setText("Teclee el Número o Nombre del Cliente:");
        panelNorteTextos.add(etiquetaInformacionEliminar);

        add(panelNorteTextos, java.awt.BorderLayout.PAGE_START);

        panelCentroTabla.setLayout(new java.awt.BorderLayout());

        campoCliente.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        panelCentroTabla.add(campoCliente, java.awt.BorderLayout.PAGE_START);

        panelTabla.setPreferredSize(new java.awt.Dimension(454, 200));

        tablaClientes.setBackground(new java.awt.Color(192, 236, 245));
        tablaClientes.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tablaClientes);

        panelCentroTabla.add(panelTabla, java.awt.BorderLayout.CENTER);

        add(panelCentroTabla, java.awt.BorderLayout.CENTER);

        panelBoton.setBackground(new java.awt.Color(192, 236, 245));
        panelBoton.setLayout(new java.awt.BorderLayout(0, 10));

        botonAceptar.setBackground(new java.awt.Color(255, 195, 66));
        botonAceptar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar (3).png"))); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.setPreferredSize(new java.awt.Dimension(97, 50));
        panelBoton.add(botonAceptar, java.awt.BorderLayout.PAGE_END);

        add(panelBoton, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the tablaClientes
     */
    public javax.swing.JTable getTablaClientes() {
        return tablaClientes;
    }
    
    public javax.swing.JTextField getCampoCliente() {
        return campoCliente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JLabel etiquetaEliminarCliente;
    private javax.swing.JLabel etiquetaInformacionEliminar;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCentroTabla;
    private javax.swing.JPanel panelNorteTextos;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables

}
