/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.clientes;

import controladores.clientes.OyenteBuscarCliente;
import controladores.ventas.OyenteBuscarProducto;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.Venta;
import modelos.db.SQLVentas;

/**
 *
 * @author jarv
 */
public class VentanaBuscarCliente extends javax.swing.JDialog {
    
    private JLabel etiquetaNombreCliente;
    private Cliente cliente;

    /**
     * Creates new form VentanaBuscar
     */
    public VentanaBuscarCliente(SQLVentas sqlVentas, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sqlVentas.setDefaultModeloTablaBuscarCliente((DefaultTableModel) this.tablaBuscarCliente.getModel());
        addEventos(new OyenteBuscarCliente(sqlVentas, this));
    }
    
    public final void addEventos(OyenteBuscarCliente oyente) {
        this.tablaBuscarCliente.addKeyListener(oyente);
        this.botonAceptar.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
        this.campoBuscarCliente.addKeyListener(oyente);
        this.campoBuscarCliente.getDocument().addDocumentListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLineBorder = new javax.swing.JPanel();
        panelNorte = new javax.swing.JPanel();
        etiquetaBuscarCliente = new javax.swing.JLabel();
        campoBuscarCliente = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tablaBuscarCliente = new javax.swing.JTable();
        panelSur = new javax.swing.JPanel();
        panelBotonAceptar = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        panelBotonCancelar = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelLineBorder.setBackground(new java.awt.Color(192, 236, 245));
        panelLineBorder.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelLineBorder.setLayout(new java.awt.BorderLayout());

        panelNorte.setBackground(new java.awt.Color(192, 236, 245));
        panelNorte.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaBuscarCliente.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaBuscarCliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaBuscarCliente.setText("Teclee el nombre o telefono del cliente");
        panelNorte.add(etiquetaBuscarCliente);

        campoBuscarCliente.setPreferredSize(new java.awt.Dimension(10, 40));
        panelNorte.add(campoBuscarCliente);

        panelLineBorder.add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setLayout(new java.awt.BorderLayout());

        tablaBuscarCliente.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaBuscarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Numero de Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tablaBuscarCliente);

        panelCentro.add(panelTabla, java.awt.BorderLayout.CENTER);

        panelLineBorder.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setBackground(new java.awt.Color(192, 236, 245));
        panelSur.setLayout(new java.awt.BorderLayout());

        panelBotonAceptar.setBackground(new java.awt.Color(192, 236, 245));

        botonAceptar.setBackground(new java.awt.Color(255, 195, 66));
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar (3).png"))); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonAceptar.add(botonAceptar);

        panelSur.add(panelBotonAceptar, java.awt.BorderLayout.WEST);

        panelBotonCancelar.setBackground(new java.awt.Color(192, 236, 245));

        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonCancelar.add(botonCancelar);

        panelSur.add(panelBotonCancelar, java.awt.BorderLayout.EAST);

        panelLineBorder.add(panelSur, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelLineBorder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTablaBuscarCliente() {
        return tablaBuscarCliente;
    }
    
    public JTextField getCampoBuscarCliente() {
        return campoBuscarCliente;
    }
    
    public void setEtiquetaNombreCliente(JLabel etiquetaNombreCliente) {
        this.etiquetaNombreCliente = etiquetaNombreCliente;
    }
    
    public JLabel getEtiquetaNombreCliente() {
        return etiquetaNombreCliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    public Cliente getCliente() {
        return cliente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoBuscarCliente;
    private javax.swing.JLabel etiquetaBuscarCliente;
    private javax.swing.JPanel panelBotonAceptar;
    private javax.swing.JPanel panelBotonCancelar;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelLineBorder;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
