/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.clientes;

import controladores.clientes.OyenteCamposModificarCliente;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelos.db.SQLClientes;

/**
 *
 * @author jarv
 */
public class VentanaCamposModificarCliente extends javax.swing.JDialog {
    
    private long telefono;
    private JTable tablaClientes;
    private JTextField campoClientes;

    /**
     * Creates new form VentanaCamposModificarCliente
     */
    public VentanaCamposModificarCliente(SQLClientes sqlClientes, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addEventos(new OyenteCamposModificarCliente(sqlClientes, this));
    }

    public final void addEventos(OyenteCamposModificarCliente oyente) {
        this.botonCancelar.addActionListener(oyente);
        this.botonGuardarCambiosCliente.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexos = new javax.swing.ButtonGroup();
        panelBorderLine = new javax.swing.JPanel();
        panelSurBotones = new javax.swing.JPanel();
        botonGuardarCambiosCliente = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        panelCentroCampos = new javax.swing.JPanel();
        panelEtiquetas = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaApellidoP = new javax.swing.JLabel();
        etiquetaApellidoM = new javax.swing.JLabel();
        etiquetaSexo = new javax.swing.JLabel();
        etiquetaTelefono = new javax.swing.JLabel();
        etiquetaEmail = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        campoNombre = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        panelSexo = new javax.swing.JPanel();
        radioBotonM = new javax.swing.JRadioButton();
        radioBotonF = new javax.swing.JRadioButton();
        radioBotonOtro = new javax.swing.JRadioButton();
        campoTelefono = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelBorderLine.setBackground(new java.awt.Color(192, 236, 245));
        panelBorderLine.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelBorderLine.setLayout(new java.awt.BorderLayout());

        panelSurBotones.setBackground(new java.awt.Color(192, 236, 245));
        panelSurBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botonGuardarCambiosCliente.setBackground(new java.awt.Color(255, 195, 66));
        botonGuardarCambiosCliente.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonGuardarCambiosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardado.png"))); // NOI18N
        botonGuardarCambiosCliente.setText("Guardar");
        botonGuardarCambiosCliente.setToolTipText("");
        botonGuardarCambiosCliente.setName("botonGuardarCambios"); // NOI18N
        botonGuardarCambiosCliente.setPreferredSize(new java.awt.Dimension(141, 50));
        panelSurBotones.add(botonGuardarCambiosCliente);

        botonCancelar.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(98, 50));
        panelSurBotones.add(botonCancelar);

        panelBorderLine.add(panelSurBotones, java.awt.BorderLayout.PAGE_END);

        panelCentroCampos.setLayout(new java.awt.BorderLayout());

        panelEtiquetas.setBackground(new java.awt.Color(192, 236, 245));
        panelEtiquetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 236, 245), 5));
        panelEtiquetas.setLayout(new java.awt.GridLayout(6, 1, 0, 7));

        etiquetaNombre.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNombre.setText("Nombre:");
        panelEtiquetas.add(etiquetaNombre);

        etiquetaApellidoP.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaApellidoP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaApellidoP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoP.setText("Apellido Paterno:");
        panelEtiquetas.add(etiquetaApellidoP);

        etiquetaApellidoM.setBackground(new java.awt.Color(192, 236, 245));
        etiquetaApellidoM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaApellidoM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoM.setText("Apellido Materno:");
        panelEtiquetas.add(etiquetaApellidoM);

        etiquetaSexo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaSexo.setText("Sexo:");
        panelEtiquetas.add(etiquetaSexo);

        etiquetaTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaTelefono.setText("Telefono:");
        panelEtiquetas.add(etiquetaTelefono);

        etiquetaEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaEmail.setText("Email:");
        panelEtiquetas.add(etiquetaEmail);

        panelCentroCampos.add(panelEtiquetas, java.awt.BorderLayout.WEST);

        panelCampos.setBackground(new java.awt.Color(192, 236, 245));
        panelCampos.setLayout(new java.awt.GridLayout(6, 1, 0, 7));

        campoNombre.setColumns(20);
        panelCampos.add(campoNombre);

        campoApellidoP.setColumns(20);
        panelCampos.add(campoApellidoP);

        campoApellidoM.setColumns(20);
        panelCampos.add(campoApellidoM);

        panelSexo.setBackground(new java.awt.Color(192, 236, 245));
        panelSexo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        radioBotonM.setBackground(new java.awt.Color(192, 236, 245));
        grupoSexos.add(radioBotonM);
        radioBotonM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        radioBotonM.setText("M");
        radioBotonM.setActionCommand("m");
        panelSexo.add(radioBotonM);

        radioBotonF.setBackground(new java.awt.Color(192, 236, 245));
        grupoSexos.add(radioBotonF);
        radioBotonF.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        radioBotonF.setText("F");
        radioBotonF.setActionCommand("f");
        panelSexo.add(radioBotonF);

        radioBotonOtro.setBackground(new java.awt.Color(192, 236, 245));
        grupoSexos.add(radioBotonOtro);
        radioBotonOtro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        radioBotonOtro.setText("Otro");
        radioBotonOtro.setActionCommand("otro");
        panelSexo.add(radioBotonOtro);

        panelCampos.add(panelSexo);

        campoTelefono.setColumns(20);
        panelCampos.add(campoTelefono);

        campoEmail.setColumns(20);
        panelCampos.add(campoEmail);

        panelCentroCampos.add(panelCampos, java.awt.BorderLayout.CENTER);

        panelBorderLine.add(panelCentroCampos, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBorderLine, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTelefonoCopia(long telefono) {
        this.telefono = telefono;
    }
    
    public long getTelefonoCopia() {
        return telefono;
    }
    
    /**
     * @return the campoApellidoM
     */
    public javax.swing.JTextField getCampoApellidoM() {
        return campoApellidoM;
    }

    /**
     * @return the campoApellidoP
     */
    public javax.swing.JTextField getCampoApellidoP() {
        return campoApellidoP;
    }

    /**
     * @return the campoEmail
     */
    public javax.swing.JTextField getCampoEmail() {
        return campoEmail;
    }

    /**
     * @return the campoNombre
     */
    public javax.swing.JTextField getCampoNombre() {
        return campoNombre;
    }

    /**
     * @return the campoTelefono
     */
    public javax.swing.JTextField getCampoTelefono() {
        return campoTelefono;
    }

    /**
     * @return the radioBotonF
     */
    public javax.swing.JRadioButton getRadioBotonF() {
        return radioBotonF;
    }

    /**
     * @return the radioBotonM
     */
    public javax.swing.JRadioButton getRadioBotonM() {
        return radioBotonM;
    }

    /**
     * @return the radioBotonOtro
     */
    public javax.swing.JRadioButton getRadioBotonOtro() {
        return radioBotonOtro;
    }

    /**
     * @return the grupoSexos
     */
    public javax.swing.ButtonGroup getGrupoSexos() {
        return grupoSexos;
    }
    
    /**
     * @return the tablaClientes
     */
    public JTable getTablaClientes() {
        return tablaClientes;
    }

    /**
     * @param tablaClientes the tablaClientes to set
     */
    public void setTablaClientes(JTable tablaClientes) {
        this.tablaClientes = tablaClientes;
    }

    /**
     * @return the campoClientes
     */
    public JTextField getCampoCliente() {
        return campoClientes;
    }

    /**
     * @param campoClientes the campoClientes to set
     */
    public void setCampoCliente(JTextField campoClientes) {
        this.campoClientes = campoClientes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardarCambiosCliente;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel etiquetaApellidoM;
    private javax.swing.JLabel etiquetaApellidoP;
    private javax.swing.JLabel etiquetaEmail;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaSexo;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.ButtonGroup grupoSexos;
    private javax.swing.JPanel panelBorderLine;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelCentroCampos;
    private javax.swing.JPanel panelEtiquetas;
    private javax.swing.JPanel panelSexo;
    private javax.swing.JPanel panelSurBotones;
    private javax.swing.JRadioButton radioBotonF;
    private javax.swing.JRadioButton radioBotonM;
    private javax.swing.JRadioButton radioBotonOtro;
    // End of variables declaration//GEN-END:variables

}
