/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.reportes;

import controladores.reportes.OyenteComboReportes;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import modelos.db.SQLReportes;

/**
 *
 * @author jarv
 */
public class PanelReportes extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelReportes() {
        initComponents();
        addEventos();
        this.comboMeses.setEnabled(false);
    }

    public final void addEventos() {
        SQLReportes reportes = new SQLReportes();
        OyenteComboReportes oyenteComboFiltros = new OyenteComboReportes(reportes, this);
        this.comboFiltros.addActionListener(oyenteComboFiltros);
        this.comboMeses.addActionListener(oyenteComboFiltros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        comboFiltros = new javax.swing.JComboBox<>();
        comboMeses = new javax.swing.JComboBox<>();
        panelCentro = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(116, 215, 205));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 0, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        panelNorte.setBackground(new java.awt.Color(116, 215, 205));
        panelNorte.setLayout(new java.awt.GridLayout(2, 2));

        comboFiltros.setName("comboFiltros"); // NOI18N
        panelNorte.add(comboFiltros);

        comboMeses.setName("comboFiltros"); // NOI18N
        panelNorte.add(comboMeses);

        add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelCentro.setBackground(new java.awt.Color(192, 236, 245));
        panelCentro.setLayout(new java.awt.BorderLayout());

        panelTabla.setPreferredSize(new java.awt.Dimension(454, 200));

        tablaClientes.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tablaClientes);

        panelCentro.add(panelTabla, java.awt.BorderLayout.CENTER);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelCentro() {
        return panelCentro;
    }
    
    public JPanel getPanelNorte() {
        return panelNorte;
    }
    
    public JComboBox getComboFiltros() {
        return comboFiltros;
    }  
    
    public JComboBox getComboFechas() {
        return comboMeses;
    }  
    
    public JTable getTablaReportes() {
        return tablaClientes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFiltros;
    private javax.swing.JComboBox<String> comboMeses;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
