/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.usuarios;

import vistas.clientes.*;
import controladores.clientes.OyenteEliminarCliente;
import controladores.usuarios.OyenteEliminarUsuario;
import modelos.db.SQLClientes;
import modelos.db.SQLUsuario;

/**
 *
 * @author jarv
 */
public class PanelEliminarUsuario extends javax.swing.JPanel {
   
    /**
     * Creates new form PanelModificarCliente
     */
    public PanelEliminarUsuario(SQLUsuario sqlUsuario) {
        initComponents();
        addEventos(new OyenteEliminarUsuario(sqlUsuario, this));
    }

    public final void addEventos(OyenteEliminarUsuario oyente) {
        this.botonAceptar.addActionListener(oyente);
        this.campoUsuario.getDocument().addDocumentListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorteTextos = new javax.swing.JPanel();
        etiquetaEliminarUsuario = new javax.swing.JLabel();
        etiquetaInformacionEliminar = new javax.swing.JLabel();
        panelCentroTabla = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        panelTabla = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        panelBoton = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 194, 227));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorteTextos.setBackground(new java.awt.Color(243, 194, 227));
        panelNorteTextos.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaEliminarUsuario.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaEliminarUsuario.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        etiquetaEliminarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaEliminarUsuario.setText("Eliminar Usuario");
        panelNorteTextos.add(etiquetaEliminarUsuario);

        etiquetaInformacionEliminar.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaInformacionEliminar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaInformacionEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaInformacionEliminar.setText("Teclee el Número o Nombre del Usuario:");
        panelNorteTextos.add(etiquetaInformacionEliminar);

        add(panelNorteTextos, java.awt.BorderLayout.PAGE_START);

        panelCentroTabla.setLayout(new java.awt.BorderLayout());

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        panelCentroTabla.add(campoUsuario, java.awt.BorderLayout.PAGE_START);

        panelTabla.setPreferredSize(new java.awt.Dimension(454, 200));

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "NICK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tablaUsuario);

        panelCentroTabla.add(panelTabla, java.awt.BorderLayout.CENTER);

        add(panelCentroTabla, java.awt.BorderLayout.CENTER);

        panelBoton.setBackground(new java.awt.Color(243, 194, 227));
        panelBoton.setLayout(new java.awt.BorderLayout(0, 10));

        botonAceptar.setBackground(new java.awt.Color(255, 195, 66));
        botonAceptar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar (3).png"))); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.setPreferredSize(new java.awt.Dimension(97, 50));
        panelBoton.add(botonAceptar, java.awt.BorderLayout.PAGE_END);

        add(panelBoton, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    /**
     * @return the tablaClientes
     */
    public javax.swing.JTable getTablaUsuario() {
        return tablaUsuario;
    }
    
    public javax.swing.JTextField getCampoUsuario() {
        return campoUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiquetaEliminarUsuario;
    private javax.swing.JLabel etiquetaInformacionEliminar;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCentroTabla;
    private javax.swing.JPanel panelNorteTextos;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaUsuario;
    // End of variables declaration//GEN-END:variables

}
