/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.usuarios;

import controladores.usuarios.OyenteModificarUsuario;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelos.db.SQLUsuario;

/**
 *
 * @author jarv
 */
public class PanelModificarUsuario extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelModificarCliente
     */
    public PanelModificarUsuario(SQLUsuario sqlUsuario) {
        initComponents();
        addEventos(new OyenteModificarUsuario(sqlUsuario, this));
    }
    
    public void addEventos(OyenteModificarUsuario oyente){
        this.botonAceptar.addActionListener(oyente);
        this.campoUsuario.getDocument().addDocumentListener(oyente);
        
    }

    public JTable getTablaUsuario() {
        return tablaUsuario;
    }

    public JTextField getCampoUsuario() {
        return campoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorteTextos = new javax.swing.JPanel();
        etiquetaModificarUsuario = new javax.swing.JLabel();
        etiquetaInformacionModificar = new javax.swing.JLabel();
        panelCentroTabla = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        campoUsuario = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 194, 227));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorteTextos.setBackground(new java.awt.Color(243, 194, 227));
        panelNorteTextos.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaModificarUsuario.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaModificarUsuario.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        etiquetaModificarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaModificarUsuario.setText("Modificar Usuario");
        panelNorteTextos.add(etiquetaModificarUsuario);

        etiquetaInformacionModificar.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaInformacionModificar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaInformacionModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaInformacionModificar.setText("Teclee el Número o Nombre del Usuario:");
        panelNorteTextos.add(etiquetaInformacionModificar);

        add(panelNorteTextos, java.awt.BorderLayout.PAGE_START);

        panelCentroTabla.setBackground(new java.awt.Color(243, 194, 227));
        panelCentroTabla.setLayout(new java.awt.BorderLayout());

        panelTabla.setPreferredSize(new java.awt.Dimension(454, 300));

        tablaUsuario.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDO M", "APELLIDO P", "NICK"
            }
        ));
        panelTabla.setViewportView(tablaUsuario);

        panelCentroTabla.add(panelTabla, java.awt.BorderLayout.CENTER);

        campoUsuario.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        panelCentroTabla.add(campoUsuario, java.awt.BorderLayout.PAGE_START);

        add(panelCentroTabla, java.awt.BorderLayout.CENTER);

        panelBoton.setBackground(new java.awt.Color(243, 194, 227));
        panelBoton.setLayout(new java.awt.BorderLayout(0, 10));

        botonAceptar.setBackground(new java.awt.Color(255, 195, 66));
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar (3).png"))); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setName("aceptar"); // NOI18N
        botonAceptar.setPreferredSize(new java.awt.Dimension(97, 50));
        panelBoton.add(botonAceptar, java.awt.BorderLayout.PAGE_END);

        add(panelBoton, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiquetaInformacionModificar;
    private javax.swing.JLabel etiquetaModificarUsuario;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCentroTabla;
    private javax.swing.JPanel panelNorteTextos;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaUsuario;
    // End of variables declaration//GEN-END:variables
}
