/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.usuarios;

import controladores.usuarios.OyenteNuevoUsuario;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelos.db.SQLUsuario;

/**
 *
 * @author jarv
 */
public class PanelNuevoUsuario extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelNuevoCliente
     */
    public PanelNuevoUsuario(SQLUsuario sqlUsuario) {
        initComponents();
        OyenteNuevoUsuario oyente = new OyenteNuevoUsuario(sqlUsuario,this);
        addOyente(oyente);
    }
    
   public void addOyente(OyenteNuevoUsuario e ){
        this.botonGuardarUsuario.addActionListener(e);
        this.botonCancelar.addActionListener(e);
        this.botonGuardarUsuario.setName("guardar");
        this.botonCancelar.setName("cancelar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorteNuevoUsuario = new javax.swing.JPanel();
        etiquetaNuevoUsuario = new javax.swing.JLabel();
        etiquetaInformacion = new javax.swing.JLabel();
        panelCentroCampos = new javax.swing.JPanel();
        panelEtiquetas = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaApellidoP = new javax.swing.JLabel();
        etiquetaApellidoM = new javax.swing.JLabel();
        etiquetaNUsuario = new javax.swing.JLabel();
        etiquetaContraseña = new javax.swing.JLabel();
        etiquetaCargo = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        campoNombre = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        campoContrseña = new javax.swing.JTextField();
        comboCargo = new javax.swing.JComboBox<>();
        panelSurBotones = new javax.swing.JPanel();
        botonGuardarUsuario = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 194, 227));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorteNuevoUsuario.setBackground(new java.awt.Color(243, 194, 227));
        panelNorteNuevoUsuario.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaNuevoUsuario.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaNuevoUsuario.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        etiquetaNuevoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNuevoUsuario.setText("Nuevo Usuario");
        panelNorteNuevoUsuario.add(etiquetaNuevoUsuario);

        etiquetaInformacion.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaInformacion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaInformacion.setText("-Llene la siguiente información acerca del usuario");
        panelNorteNuevoUsuario.add(etiquetaInformacion);

        add(panelNorteNuevoUsuario, java.awt.BorderLayout.NORTH);

        panelCentroCampos.setLayout(new java.awt.BorderLayout());

        panelEtiquetas.setBackground(new java.awt.Color(243, 194, 227));
        panelEtiquetas.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelEtiquetas.setLayout(new java.awt.GridLayout(6, 1, 0, 7));

        etiquetaNombre.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNombre.setText("Nombre:");
        panelEtiquetas.add(etiquetaNombre);

        etiquetaApellidoP.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaApellidoP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaApellidoP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoP.setText("Apellido Paterno:");
        panelEtiquetas.add(etiquetaApellidoP);

        etiquetaApellidoM.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaApellidoM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaApellidoM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoM.setText("Apellido Materno:");
        panelEtiquetas.add(etiquetaApellidoM);

        etiquetaNUsuario.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaNUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaNUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNUsuario.setText("Nombre de Usuario:");
        panelEtiquetas.add(etiquetaNUsuario);

        etiquetaContraseña.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaContraseña.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaContraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaContraseña.setText("Contraseña:");
        panelEtiquetas.add(etiquetaContraseña);

        etiquetaCargo.setBackground(new java.awt.Color(243, 194, 227));
        etiquetaCargo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaCargo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaCargo.setText("Cargo:");
        panelEtiquetas.add(etiquetaCargo);

        panelCentroCampos.add(panelEtiquetas, java.awt.BorderLayout.WEST);

        panelCampos.setBackground(new java.awt.Color(243, 194, 227));
        panelCampos.setLayout(new java.awt.GridLayout(6, 1, 0, 7));

        campoNombre.setColumns(20);
        panelCampos.add(campoNombre);

        campoApellidoP.setColumns(20);
        panelCampos.add(campoApellidoP);

        campoApellidoM.setColumns(20);
        panelCampos.add(campoApellidoM);

        campoUsuario.setColumns(20);
        panelCampos.add(campoUsuario);

        campoContrseña.setColumns(20);
        panelCampos.add(campoContrseña);

        comboCargo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador" }));
        comboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCargoActionPerformed(evt);
            }
        });
        panelCampos.add(comboCargo);

        panelCentroCampos.add(panelCampos, java.awt.BorderLayout.CENTER);

        add(panelCentroCampos, java.awt.BorderLayout.CENTER);

        panelSurBotones.setBackground(new java.awt.Color(243, 194, 227));
        panelSurBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botonGuardarUsuario.setBackground(new java.awt.Color(255, 195, 66));
        botonGuardarUsuario.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonGuardarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardado.png"))); // NOI18N
        botonGuardarUsuario.setText("Guardar");
        botonGuardarUsuario.setPreferredSize(new java.awt.Dimension(141, 50));
        panelSurBotones.add(botonGuardarUsuario);

        botonCancelar.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(98, 50));
        panelSurBotones.add(botonCancelar);

        add(panelSurBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void comboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCargoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardarUsuario;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoContrseña;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JLabel etiquetaApellidoM;
    private javax.swing.JLabel etiquetaApellidoP;
    private javax.swing.JLabel etiquetaCargo;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaInformacion;
    private javax.swing.JLabel etiquetaNUsuario;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNuevoUsuario;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelCentroCampos;
    private javax.swing.JPanel panelEtiquetas;
    private javax.swing.JPanel panelNorteNuevoUsuario;
    private javax.swing.JPanel panelSurBotones;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoApellidoM() {
        return campoApellidoM;
    }

    public JTextField getCampoApellidoP() {
        return campoApellidoP;
    }

    public JTextField getCampoContrseña() {
        return campoContrseña;
    }

    public JTextField getCampoNombre() {
        return campoNombre;
    }

    public JTextField getCampoUsuario() {
        return campoUsuario;
    }

    public JComboBox<String> getComboCargo() {
        return comboCargo;
    }

}
