/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.usuarios;

import controladores.usuarios.OyenteCamposModificarUsuario;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelos.db.SQLUsuario;

/**
 *
 * @author jarv
 */
public class VentanaCamposModificarUsuario extends javax.swing.JDialog {
    
    private String nick;
    private JTable tablaUsuario;
    private JTextField campoUsuario;

    /**
     * Creates new form VentanaCamposModificarCliente
     */
    public VentanaCamposModificarUsuario(SQLUsuario sqlUsuario, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addEventos(new OyenteCamposModificarUsuario(sqlUsuario, this));
    }

    public final void addEventos(OyenteCamposModificarUsuario oyente) {
        this.botonCancelar.addActionListener(oyente);
        this.botonGuardarCambiosCliente.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexos = new javax.swing.ButtonGroup();
        panelBorderLine = new javax.swing.JPanel();
        panelSurBotones = new javax.swing.JPanel();
        botonGuardarCambiosCliente = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        panelCentroCampos = new javax.swing.JPanel();
        panelEtiquetas = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaApellidoP = new javax.swing.JLabel();
        etiquetaApellidoM = new javax.swing.JLabel();
        etiquetaNick = new javax.swing.JLabel();
        etiquetaEmail = new javax.swing.JLabel();
        etiquetaCargo = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        campoNombre = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        campoNick = new javax.swing.JTextField();
        campoContrasenal = new javax.swing.JTextField();
        comboCargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelBorderLine.setBackground(new java.awt.Color(243, 194, 227));
        panelBorderLine.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelBorderLine.setLayout(new java.awt.BorderLayout());

        panelSurBotones.setBackground(new java.awt.Color(243, 194, 227));
        panelSurBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botonGuardarCambiosCliente.setBackground(new java.awt.Color(255, 195, 66));
        botonGuardarCambiosCliente.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonGuardarCambiosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardado.png"))); // NOI18N
        botonGuardarCambiosCliente.setText("Guardar");
        botonGuardarCambiosCliente.setToolTipText("");
        botonGuardarCambiosCliente.setName("botonGuardarCambios"); // NOI18N
        botonGuardarCambiosCliente.setPreferredSize(new java.awt.Dimension(141, 50));
        panelSurBotones.add(botonGuardarCambiosCliente);

        botonCancelar.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelar.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(98, 50));
        panelSurBotones.add(botonCancelar);

        panelBorderLine.add(panelSurBotones, java.awt.BorderLayout.PAGE_END);

        panelCentroCampos.setBackground(new java.awt.Color(243, 194, 227));
        panelCentroCampos.setLayout(new java.awt.BorderLayout());

        panelEtiquetas.setBackground(new java.awt.Color(243, 194, 227));
        panelEtiquetas.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        etiquetaNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNombre.setText("Nombre:");
        panelEtiquetas.add(etiquetaNombre);

        etiquetaApellidoP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaApellidoP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoP.setText("Apellido Paterno:");
        panelEtiquetas.add(etiquetaApellidoP);

        etiquetaApellidoM.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaApellidoM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaApellidoM.setText("Apellido Materno:");
        panelEtiquetas.add(etiquetaApellidoM);

        etiquetaNick.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaNick.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNick.setText("Nick:");
        panelEtiquetas.add(etiquetaNick);

        etiquetaEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaEmail.setText("Contraseña:");
        panelEtiquetas.add(etiquetaEmail);

        etiquetaCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaCargo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaCargo.setText("Cargo:");
        panelEtiquetas.add(etiquetaCargo);

        panelCentroCampos.add(panelEtiquetas, java.awt.BorderLayout.WEST);

        panelCampos.setBackground(new java.awt.Color(243, 194, 227));
        panelCampos.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        campoNombre.setColumns(20);
        panelCampos.add(campoNombre);

        campoApellidoP.setColumns(20);
        panelCampos.add(campoApellidoP);

        campoApellidoM.setColumns(20);
        panelCampos.add(campoApellidoM);

        campoNick.setColumns(20);
        panelCampos.add(campoNick);

        campoContrasenal.setColumns(20);
        panelCampos.add(campoContrasenal);

        comboCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCampos.add(comboCargo);

        panelCentroCampos.add(panelCampos, java.awt.BorderLayout.CENTER);

        panelBorderLine.add(panelCentroCampos, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBorderLine, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setNick(String nick){
        this.nick = nick;
    }
    public String getNick(){
        return nick;
    }
    
    public JTextField getCampoUsuario() {
        return campoUsuario;
    }

    public void setCampoUsuario(JTextField campoUsuario) {
        this.campoUsuario = campoUsuario;
    }

    public JTextField getCampoApellidoM() {
        return campoApellidoM;
    }

    public void setCampoApellidoM(JTextField campoApellidoM) {
        this.campoApellidoM = campoApellidoM;
    }

    public JTextField getCampoApellidoP() {
        return campoApellidoP;
    }

    public void setCampoApellidoP(JTextField campoApellidoP) {
        this.campoApellidoP = campoApellidoP;
    }

    public JTextField getCampoContrasenal() {
        return campoContrasenal;
    }

    public void setCampoContrasenal(JTextField campoContrasenal) {
        this.campoContrasenal = campoContrasenal;
    }

    public JTextField getCampoNick() {
        return campoNick;
    }

    public void setCampoNick(JTextField campoNick) {
        this.campoNick = campoNick;
    }

    public JTextField getCampoNombre() {
        return campoNombre;
    }

    public void setCampoNombre(JTextField campoNombre) {
        this.campoNombre = campoNombre;
    }

    public JComboBox<String> getComboCargo() {
        return comboCargo;
    }

    public void setComboCargo(JComboBox<String> comboCargo) {
        this.comboCargo = comboCargo;
    }

    public JTable getTablaUsuario() {
        return tablaUsuario;
    }

    public void setTablaUsuario(JTable tablaUsuario) {
        this.tablaUsuario = tablaUsuario;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardarCambiosCliente;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoContrasenal;
    private javax.swing.JTextField campoNick;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JLabel etiquetaApellidoM;
    private javax.swing.JLabel etiquetaApellidoP;
    private javax.swing.JLabel etiquetaCargo;
    private javax.swing.JLabel etiquetaEmail;
    private javax.swing.JLabel etiquetaNick;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.ButtonGroup grupoSexos;
    private javax.swing.JPanel panelBorderLine;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelCentroCampos;
    private javax.swing.JPanel panelEtiquetas;
    private javax.swing.JPanel panelSurBotones;
    // End of variables declaration//GEN-END:variables

}
