/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.g;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JTable;
import modelos.g.CargarCategorias;

/**
 *
 * @author GenaroLM
 */
public class VCatalogo extends javax.swing.JPanel {
    
    private CargarCategorias cargaC;

    /**
     * Creates new form VentanaCatalogo
     */
    public VCatalogo() {
        initComponents();
    }
    
    public void addEventos(ActionListener e){
        this.comboDepartamentoC.addActionListener(e);
        this.comboDepartamentoC.setName("categoria");
        cargaC = new CargarCategorias();
        cargarCategorias();
    }
    
    public void cargarCategorias() {
        cargaC.consultaCategorias();
        try{
            while(cargaC.getRs().next()){
                this.getComboDepartamentoC().addItem(cargaC.getRs().getString("NOMBRE_CATEGORIA"));  
            }
        }catch(SQLException ex){
            System.out.println("En evento de ventana: "+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCatalogo = new javax.swing.JPanel();
        panelSuperiorC = new javax.swing.JPanel();
        etiquetaC1 = new javax.swing.JLabel();
        comboDepartamentoC = new javax.swing.JComboBox<>();
        panelCentralC = new javax.swing.JScrollPane();
        tablaC = new javax.swing.JTable();

        setBackground(new java.awt.Color(178, 230, 123));

        panelCatalogo.setBackground(new java.awt.Color(178, 230, 123));
        panelCatalogo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catálogo de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 24))); // NOI18N
        panelCatalogo.setLayout(new java.awt.BorderLayout());

        panelSuperiorC.setBackground(new java.awt.Color(178, 230, 123));

        etiquetaC1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        etiquetaC1.setText("Departamento");
        panelSuperiorC.add(etiquetaC1);

        comboDepartamentoC.setBackground(new java.awt.Color(255, 195, 66));
        comboDepartamentoC.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        comboDepartamentoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODO" }));
        panelSuperiorC.add(comboDepartamentoC);

        panelCatalogo.add(panelSuperiorC, java.awt.BorderLayout.NORTH);

        panelCentralC.setBackground(new java.awt.Color(178, 230, 123));
        panelCentralC.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelCentralC.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        panelCentralC.setMaximumSize(new java.awt.Dimension(50000, 32767));
        panelCentralC.setMinimumSize(new java.awt.Dimension(100, 100));
        panelCentralC.setPreferredSize(new java.awt.Dimension(1300,500));

        tablaC.setBackground(getBackground());
        tablaC.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "COLOR", "TAMAÑO", "MARCA", "DESCRIPCIÓN", "EXISTENCIA", "DEPARTAMENTO", "COSTO COMPRA", "PRECIO VENTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaC.setEnabled(false);
        tablaC.setShowHorizontalLines(false);
        tablaC.setShowVerticalLines(false);
        tablaC.getTableHeader().setReorderingAllowed(false);
        panelCentralC.setViewportView(tablaC);
        if (tablaC.getColumnModel().getColumnCount() > 0) {
            tablaC.getColumnModel().getColumn(0).setResizable(false);
            tablaC.getColumnModel().getColumn(1).setResizable(false);
            tablaC.getColumnModel().getColumn(2).setResizable(false);
            tablaC.getColumnModel().getColumn(3).setResizable(false);
            tablaC.getColumnModel().getColumn(4).setResizable(false);
            tablaC.getColumnModel().getColumn(5).setResizable(false);
            tablaC.getColumnModel().getColumn(6).setResizable(false);
        }

        panelCatalogo.add(panelCentralC, java.awt.BorderLayout.CENTER);

        add(panelCatalogo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDepartamentoC;
    private javax.swing.JLabel etiquetaC1;
    private javax.swing.JPanel panelCatalogo;
    private javax.swing.JScrollPane panelCentralC;
    private javax.swing.JPanel panelSuperiorC;
    private javax.swing.JTable tablaC;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getComboDepartamentoC() {
        return comboDepartamentoC;
    }

    public JTable getTablaC() {
        return tablaC;
    }

    
}
