/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.g;

import controladores.g.ControladorC;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextField;
import modelos.g.CargarCategorias;

/**
 *
 * @author GenaroLM
 */
public class VCategoria extends javax.swing.JPanel {
    
    private CargarCategorias cargarC;

    /**
     * Creates new form DepartamentosProductos
     */
    public VCategoria() {
        initComponents();
//        cargarCategorias();
    }
    public void addEventos(ControladorC e){
        this.botonGuardarD.addActionListener(e);
        this.botonCancelarD.addActionListener(e);
        this.botonEliminarD.addActionListener(e);
         this.campoBusquedaD.getDocument().addDocumentListener(e);
        this.botonGuardarD.setName("guardar");
        this.botonCancelarD.setName("cancelar");
        this.botonEliminarD.setName("eliminar");
        
        cargarC = new CargarCategorias();
        cargarCategorias();
    }
    
    public void cargarCategorias(){
        cargarC.consultaCategorias();
        try{
            DefaultListModel modelo = new DefaultListModel();
            String v[] = new String[1];
            
            while(cargarC.getRs().next()){       
                v[0] = cargarC.getRs().getString("NOMBRE_CATEGORIA");
                modelo.addElement(v[0]);
                this.getListaInternaD().setModel(modelo); 
            }
        }catch(SQLException ex){
            System.out.println("En evento de ventana: "+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDepartamento = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        campoBusquedaD = new javax.swing.JTextField();
        listaD = new javax.swing.JScrollPane();
        listaInternaD = new javax.swing.JList<>();
        panelDerecho = new javax.swing.JPanel();
        panelSuperiorD = new javax.swing.JPanel();
        botonEliminarD = new javax.swing.JButton();
        panelInferiorD = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        etiquetaNombreD = new javax.swing.JLabel();
        campoNombreD = new javax.swing.JTextField();
        panelOpcionesD = new javax.swing.JPanel();
        botonGuardarD = new javax.swing.JButton();
        botonCancelarD = new javax.swing.JButton();

        setBackground(new java.awt.Color(211, 249, 170));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));

        panelDepartamento.setBackground(new java.awt.Color(211, 249, 170));
        panelDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorías", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 0, 24))); // NOI18N
        panelDepartamento.setLayout(new java.awt.GridLayout(1, 2));

        panelIzquierdo.setBackground(new java.awt.Color(211, 249, 170));
        panelIzquierdo.setLayout(new java.awt.BorderLayout());

        campoBusquedaD.setColumns(15);
        panelIzquierdo.add(campoBusquedaD, java.awt.BorderLayout.NORTH);

        listaInternaD.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaInternaD.setToolTipText("");
        listaD.setViewportView(listaInternaD);

        panelIzquierdo.add(listaD, java.awt.BorderLayout.CENTER);

        panelDepartamento.add(panelIzquierdo);

        panelDerecho.setBackground(new java.awt.Color(211, 249, 170));
        panelDerecho.setLayout(new java.awt.BorderLayout());

        panelSuperiorD.setBackground(new java.awt.Color(211, 249, 170));

        botonEliminarD.setBackground(new java.awt.Color(255, 195, 66));
        botonEliminarD.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonEliminarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        botonEliminarD.setText("Eliminar");
        botonEliminarD.setPreferredSize(new java.awt.Dimension(150, 30));
        panelSuperiorD.add(botonEliminarD);

        panelDerecho.add(panelSuperiorD, java.awt.BorderLayout.NORTH);

        panelInferiorD.setBackground(new java.awt.Color(211, 249, 170));
        panelInferiorD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 18))); // NOI18N
        panelInferiorD.setLayout(new java.awt.GridLayout(3, 1));

        panelNombre.setBackground(new java.awt.Color(211, 249, 170));
        panelNombre.setLayout(new java.awt.GridLayout(2, 1));

        etiquetaNombreD.setBackground(new java.awt.Color(211, 249, 170));
        etiquetaNombreD.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaNombreD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombreD.setText("Nombre:");
        panelNombre.add(etiquetaNombreD);

        campoNombreD.setColumns(15);
        panelNombre.add(campoNombreD);

        panelInferiorD.add(panelNombre);

        panelOpcionesD.setBackground(new java.awt.Color(211, 249, 170));

        botonGuardarD.setBackground(new java.awt.Color(255, 195, 66));
        botonGuardarD.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonGuardarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        botonGuardarD.setText("Guardar Departamento");
        botonGuardarD.setPreferredSize(new java.awt.Dimension(230, 30));
        panelOpcionesD.add(botonGuardarD);

        botonCancelarD.setBackground(new java.awt.Color(255, 195, 66));
        botonCancelarD.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        botonCancelarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        botonCancelarD.setPreferredSize(new java.awt.Dimension(150, 30));
        panelOpcionesD.add(botonCancelarD);

        panelInferiorD.add(panelOpcionesD);

        panelDerecho.add(panelInferiorD, java.awt.BorderLayout.CENTER);

        panelDepartamento.add(panelDerecho);

        add(panelDepartamento);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarD;
    private javax.swing.JButton botonEliminarD;
    private javax.swing.JButton botonGuardarD;
    private javax.swing.JTextField campoBusquedaD;
    private javax.swing.JTextField campoNombreD;
    private javax.swing.JLabel etiquetaNombreD;
    private javax.swing.JScrollPane listaD;
    private javax.swing.JList<String> listaInternaD;
    private javax.swing.JPanel panelDepartamento;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelInferiorD;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelOpcionesD;
    private javax.swing.JPanel panelSuperiorD;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoBusquedaD() {
        return campoBusquedaD;
    }

    public JTextField getCampoNombreD() {
        return campoNombreD;
    }

    public JList<String> getListaInternaD() {
        return listaInternaD;
    }

    

}
