/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.proveedor;

import controladores.proveedor.*;
import BaseDatos.SQLProveedores;

/**
 *
 * @author jarv
 */
public class PanelNuevoProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuevoCliente
     */
    public PanelNuevoProveedor(SQLProveedores sqlProveedores) {
        initComponents();
        addEventos(new OyenteNuevoProveedor(sqlProveedores, this));
    }
    
    public final void addEventos(OyenteNuevoProveedor oyente) {
        this.botonGuardarProveedor.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorteNuevoCliente = new javax.swing.JPanel();
        etiquetaNuevoProveedor = new javax.swing.JLabel();
        etiquetaInformacion = new javax.swing.JLabel();
        panelCentroCampos = new javax.swing.JPanel();
        panelEtiquetas = new javax.swing.JPanel();
        etiquetaCompania = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        calle = new javax.swing.JLabel();
        colonia = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        ciudad = new javax.swing.JLabel();
        codigoPostal = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        campoCompania = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoCalle = new javax.swing.JTextField();
        campoColonia = new javax.swing.JTextField();
        campoEstado = new javax.swing.JTextField();
        campoCiudad = new javax.swing.JTextField();
        campoCodigoPostal = new javax.swing.JTextField();
        panelSurBotones = new javax.swing.JPanel();
        botonGuardarProveedor = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorteNuevoCliente.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaNuevoProveedor.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        etiquetaNuevoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNuevoProveedor.setText("Nuevo Proveedor");
        panelNorteNuevoCliente.add(etiquetaNuevoProveedor);

        etiquetaInformacion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaInformacion.setText("- Llene la siguiente información acerca del Proveedor");
        panelNorteNuevoCliente.add(etiquetaInformacion);

        add(panelNorteNuevoCliente, java.awt.BorderLayout.NORTH);

        panelCentroCampos.setLayout(new java.awt.BorderLayout());

        panelEtiquetas.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelEtiquetas.setLayout(new java.awt.GridLayout(8, 1, 0, 5));

        etiquetaCompania.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        etiquetaCompania.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaCompania.setText("Companía:");
        panelEtiquetas.add(etiquetaCompania);

        email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email.setText("E-mail:");
        panelEtiquetas.add(email);

        telefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefono.setText("Teléfono:");
        panelEtiquetas.add(telefono);

        calle.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        calle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calle.setText("Calle:");
        panelEtiquetas.add(calle);

        colonia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        colonia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        colonia.setText("Colonia:");
        panelEtiquetas.add(colonia);

        estado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        estado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        estado.setText("Estado:");
        panelEtiquetas.add(estado);

        ciudad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ciudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ciudad.setText("Ciudad:");
        panelEtiquetas.add(ciudad);

        codigoPostal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        codigoPostal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigoPostal.setText("Código Postal:");
        panelEtiquetas.add(codigoPostal);

        panelCentroCampos.add(panelEtiquetas, java.awt.BorderLayout.WEST);

        panelCampos.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelCampos.setLayout(new java.awt.GridLayout(8, 1, 0, 5));

        campoCompania.setColumns(20);
        panelCampos.add(campoCompania);

        campoEmail.setColumns(20);
        panelCampos.add(campoEmail);

        campoTelefono.setColumns(20);
        panelCampos.add(campoTelefono);

        campoCalle.setColumns(20);
        panelCampos.add(campoCalle);

        campoColonia.setColumns(20);
        panelCampos.add(campoColonia);

        campoEstado.setColumns(20);
        panelCampos.add(campoEstado);

        campoCiudad.setColumns(20);
        panelCampos.add(campoCiudad);

        campoCodigoPostal.setColumns(20);
        panelCampos.add(campoCodigoPostal);

        panelCentroCampos.add(panelCampos, java.awt.BorderLayout.CENTER);

        add(panelCentroCampos, java.awt.BorderLayout.CENTER);

        botonGuardarProveedor.setBackground(new java.awt.Color(102, 153, 255));
        botonGuardarProveedor.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        botonGuardarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarProveedor.setText("Guardar Proveedor");
        botonGuardarProveedor.setName("botonGuardar"); // NOI18N
        botonGuardarProveedor.setPreferredSize(new java.awt.Dimension(141, 50));
        panelSurBotones.add(botonGuardarProveedor);

        botonCancelar.setBackground(new java.awt.Color(102, 153, 255));
        botonCancelar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("Cancelar");
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(98, 50));
        panelSurBotones.add(botonCancelar);

        add(panelSurBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardarProveedor;
    private javax.swing.JLabel calle;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCiudad;
    private javax.swing.JTextField campoCodigoPostal;
    private javax.swing.JTextField campoColonia;
    private javax.swing.JTextField campoCompania;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel ciudad;
    private javax.swing.JLabel codigoPostal;
    private javax.swing.JLabel colonia;
    private javax.swing.JLabel email;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel etiquetaCompania;
    private javax.swing.JLabel etiquetaInformacion;
    private javax.swing.JLabel etiquetaNuevoProveedor;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelCentroCampos;
    private javax.swing.JPanel panelEtiquetas;
    private javax.swing.JPanel panelNorteNuevoCliente;
    private javax.swing.JPanel panelSurBotones;
    private javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the campoCalle
     */
    public javax.swing.JTextField getCampoCalle() {
        return campoCalle;
    }

    /**
     * @return the campoCiudad
     */
    public javax.swing.JTextField getCampoCiudad() {
        return campoCiudad;
    }

    /**
     * @return the campoCodigoPostal
     */
    public javax.swing.JTextField getCampoCodigoPostal() {
        return campoCodigoPostal;
    }

    /**
     * @return the campoColonia
     */
    public javax.swing.JTextField getCampoColonia() {
        return campoColonia;
    }

    /**
     * @return the campoCompania
     */
    public javax.swing.JTextField getCampoCompania() {
        return campoCompania;
    }

    /**
     * @return the campoEmail
     */
    public javax.swing.JTextField getCampoEmail() {
        return campoEmail;
    }

    /**
     * @return the campoEstado
     */
    public javax.swing.JTextField getCampoEstado() {
        return campoEstado;
    }

    /**
     * @return the campoTelefono
     */
    public javax.swing.JTextField getCampoTelefono() {
        return campoTelefono;
    }
}
