/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.proveedor;

import controladores.proveedor.*;

import BaseDatos.SQLProveedores;

/**
 *
 * @author jarv
 */
public class PanelEliminarProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelModificarCliente
     */
    public PanelEliminarProveedor(SQLProveedores sqlProveedores) {
        initComponents();
         addEventos(new OyenteEliminarProveedor(sqlProveedores, this));
    }
    public final void addEventos(OyenteEliminarProveedor oyente) {
        this.botonAceptar.addActionListener(oyente);
        this.campoProveedor.getDocument().addDocumentListener(oyente);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorteTextos = new javax.swing.JPanel();
        etiquetaEliminarProveedor = new javax.swing.JLabel();
        etiquetaInformacionEliminar = new javax.swing.JLabel();
        panelCentroTabla = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        campoProveedor = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorteTextos.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaEliminarProveedor.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        etiquetaEliminarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaEliminarProveedor.setText("Eliminar Proveedor");
        panelNorteTextos.add(etiquetaEliminarProveedor);

        etiquetaInformacionEliminar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaInformacionEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaInformacionEliminar.setText("Teclee el nombre de la compañía u otra información:");
        panelNorteTextos.add(etiquetaInformacionEliminar);

        add(panelNorteTextos, java.awt.BorderLayout.PAGE_START);

        panelCentroTabla.setLayout(new java.awt.BorderLayout());

        panelTabla.setPreferredSize(new java.awt.Dimension(454, 300));

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de la compañía", "Email", "Telefono", "Ciudad", "Estado"
            }
        ));
        panelTabla.setViewportView(tablaProveedor);

        panelCentroTabla.add(panelTabla, java.awt.BorderLayout.CENTER);
        panelCentroTabla.add(campoProveedor, java.awt.BorderLayout.PAGE_START);

        add(panelCentroTabla, java.awt.BorderLayout.CENTER);

        panelBoton.setLayout(new java.awt.BorderLayout(0, 10));

        botonAceptar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setPreferredSize(new java.awt.Dimension(97, 50));
        panelBoton.add(botonAceptar, java.awt.BorderLayout.PAGE_END);

        add(panelBoton, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField campoProveedor;
    private javax.swing.JLabel etiquetaEliminarProveedor;
    private javax.swing.JLabel etiquetaInformacionEliminar;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCentroTabla;
    private javax.swing.JPanel panelNorteTextos;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaProveedor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the campoProveedor
     */
    public javax.swing.JTextField getCampoProveedor() {
        return campoProveedor;
    }

    /**
     * @return the tablaProveedor
     */
    public javax.swing.JTable getTablaProveedor() {
        return tablaProveedor;
    }
}
