/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.proveedor;
import controladores.proveedor.*;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import Modelo.Proveedor;
import BaseDatos.SQLProveedores;
//import modelos.Venta;
//import modelos.db.SQLVentas;

/**
 *
 * @author jarv
 */
public class VentanaBuscarProveedor extends javax.swing.JDialog {
    
    private JLabel etiquetaNombreProveedor;
    private Proveedor proveedor;

    /**
     * Creates new form VentanaBuscar
     */
    public VentanaBuscarProveedor() {//SQLProveedores sqlProveedores,boolean modal
        //super(parent, modal);
        initComponents();
        addEventos(new OyenteBuscarProveedor(this));
    }
    
    public final void addEventos(OyenteBuscarProveedor oyente) {
        this.tablaBuscarProveedor.addKeyListener(oyente);
        this.botonAceptar.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
        this.campoBuscarProveedor.addKeyListener(oyente);
        this.campoBuscarProveedor.getDocument().addDocumentListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLineBorder = new javax.swing.JPanel();
        panelNorte = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoBuscarProveedor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tablaBuscarProveedor = new javax.swing.JTable();
        panelSur = new javax.swing.JPanel();
        panelBotonAceptar = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        panelBotonCancelar = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelLineBorder.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        panelLineBorder.setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Buscar proveedor");
        jPanel1.add(jLabel1);

        panelNorte.add(jPanel1);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Teclee nombre de la Compañía o ciudad:");
        jPanel2.add(jLabel2);

        campoBuscarProveedor.setText("                                                                         ");
        jPanel2.add(campoBuscarProveedor);

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Mostrar todo");
        jButton1.setToolTipText("M");
        jPanel2.add(jButton1);

        panelNorte.add(jPanel2);

        panelLineBorder.add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setLayout(new java.awt.BorderLayout());

        tablaBuscarProveedor.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaBuscarProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Compañía", "Ciudad", "Estado", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tablaBuscarProveedor);

        panelCentro.add(panelTabla, java.awt.BorderLayout.CENTER);

        panelLineBorder.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setLayout(new java.awt.BorderLayout());

        panelBotonAceptar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        botonAceptar.setBackground(new java.awt.Color(153, 153, 255));
        botonAceptar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        botonAceptar.setText("Aceptar");
        botonAceptar.setToolTipText("A");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonAceptar.add(botonAceptar);

        panelSur.add(panelBotonAceptar, java.awt.BorderLayout.WEST);

        panelBotonCancelar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        botonCancelar.setBackground(new java.awt.Color(153, 153, 255));
        botonCancelar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("Cancelar");
        botonCancelar.setToolTipText("C");
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(163, 50));
        panelBotonCancelar.add(botonCancelar);

        panelSur.add(panelBotonCancelar, java.awt.BorderLayout.EAST);

        panelLineBorder.add(panelSur, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelLineBorder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTablaBuscarProveedor() {
        return tablaBuscarProveedor;
    }
    
    public JTextField getCampoBuscarProveedor() {
        return campoBuscarProveedor;
    }
    
    public void setEtiquetaNombreProveedor(JLabel etiquetaNombreProveedor) {
        this.etiquetaNombreProveedor = etiquetaNombreProveedor;
    }
    
    public JLabel getEtiquetaNombreProveedor() {
        return etiquetaNombreProveedor;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoBuscarProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelBotonAceptar;
    private javax.swing.JPanel panelBotonCancelar;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelLineBorder;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaBuscarProveedor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the proveedor
     */
    public Proveedor getProveedor() {
        return proveedor;
    }
}
